/**
 * Static structure of the HMI Template Suite V6.0 for WinCC Unified V20.
 * Derived from the Siemens V6.0 manual (Entry ID 91174767, 10/2025).
 *
 * Pac-Forge uses this as the source of truth for:
 * - Which predefined screens exist in the Template Suite after the wizard runs
 * - Which screen windows the Template Suite wires up and what they contain
 * - Standard layout zones and their purpose (title bar, status bar, MainWindow, nav bars)
 * - The 4-level navigation model
 * - Tag conventions the Template Suite expects on the PLC side
 *
 * These values are NEVER generated by Pac-Forge — they come from the Template Suite
 * library imported via the HMI Template Suite Wizard. Pac-Forge references them by name.
 */

import type { HmiPanelConfig } from "@/types/hmi-panel";

// ---------------------------------------------------------------------------
// Layout zones — named regions in the 1001_ScreenLayout master screen
// ---------------------------------------------------------------------------

export const HMI_LAYOUT_ZONES = {
  TITLE_BAR: "titleBar",
  STATUS_BAR: "statusBar",
  MAIN_WINDOW: "mainWindow",
  MAIN_NAVIGATION: "mainNavigation",
  SUB_NAVIGATION: "subNavigation",
  THIRD_LEVEL_NAV: "thirdLevelNav",
  TAB_NAV: "tabNav",
} as const;

export type HmiLayoutZone =
  (typeof HMI_LAYOUT_ZONES)[keyof typeof HMI_LAYOUT_ZONES];

export const HMI_LAYOUT_ZONE_LABELS: Record<HmiLayoutZone, string> = {
  titleBar: "Title Bar",
  statusBar: "Status Bar",
  mainWindow: "Main Window (application area)",
  mainNavigation: "Main Navigation (1st level)",
  subNavigation: "Sub Navigation (2nd level)",
  thirdLevelNav: "Third-Level Navigation",
  tabNav: "Tab Navigation (4th level)",
};

// ---------------------------------------------------------------------------
// Predefined Template Suite screens
// These ALREADY exist in the target TIA project after the wizard runs.
// Pac-Forge references them by name, never generates them.
// ---------------------------------------------------------------------------

export const HMI_TEMPLATE_SCREENS = {
  /** Start screen and layout master — contains title bar, status bar, swContent, swMainNavigation. */
  SCREEN_LAYOUT: "1001_ScreenLayout",
  /** First-level navigation screen (Application / Messages / Settings). Loaded into swMainNavigation. */
  MAIN_NAVIGATION: "1002_MainNavigation",
  /** Second-level nav layout wrapping swSubNavContent + nav bar. Loaded into swContent. */
  SCREEN_LAYOUT_SUB_NAV: "1101_ScreenLayout_SubNav",
  /** Fourth-level tab navigation layout. Loaded into swContent when tab-nav is used. */
  SCREEN_LAYOUT_TAB_NAV: "1300_ScreenLayout_TabNav",
  /** Default application area — replaced with Pac-Forge-generated content. */
  APPLICATION: "0001_Application",
  /** Global messages / alarms page. */
  MESSAGES: "0002_Messages",
  /** Device settings page (brightness, etc.). */
  SETTINGS: "0003_Settings",
} as const;

export type HmiTemplateScreen =
  (typeof HMI_TEMPLATE_SCREENS)[keyof typeof HMI_TEMPLATE_SCREENS];

// ---------------------------------------------------------------------------
// Template Suite popup screens
// ---------------------------------------------------------------------------

export const HMI_TEMPLATE_POPUPS = {
  /** Generic popup template, 3100 prefix. */
  GENERIC_TEMPLATE: "3100_Template",
  /** Machine operating state popup (start/stop/reset/hold). */
  MACHINE_STATE: "3102_PopUp_Template_Machine_State",
  /** Parameter set / recipe popup. */
  PARAMETER_SET: "3103_PopUp_Template_Parameter_Set",
  /** Parameter settings popup. */
  PARAMETER_SETTINGS: "3200_Parameter Settings",
  /** Alerts popup. */
  ALERTS: "3300_Alerts",
} as const;

// ---------------------------------------------------------------------------
// Screen windows — dynamic content containers defined in Template Suite
// ---------------------------------------------------------------------------

export const HMI_SCREEN_WINDOWS = {
  /** Main content container in 1001_ScreenLayout (usually holds 1101_ScreenLayout_SubNav). */
  CONTENT: "swContent",
  /** Application screen container inside 1101_ScreenLayout_SubNav. */
  SUB_NAV_CONTENT: "swSubNavContent",
  /** Right-side overlay navigation in 1001_ScreenLayout (hamburger menu target). */
  MAIN_NAVIGATION: "swMainNavigation",
} as const;

export type HmiScreenWindow =
  (typeof HMI_SCREEN_WINDOWS)[keyof typeof HMI_SCREEN_WINDOWS];

// ---------------------------------------------------------------------------
// Navigation levels
// ---------------------------------------------------------------------------

export const HMI_NAV_LEVELS = {
  /** Hamburger menu overlay, top-right of title bar, loads 1002_MainNavigation. */
  MAIN: "main",
  /** Bottom bar inside 1101_ScreenLayout_SubNav. */
  SUB: "sub",
  /** Left sidebar, optional. */
  THIRD: "third",
  /** Top tabs, optional, uses 1300_ScreenLayout_TabNav. */
  TAB: "tab",
} as const;

export type HmiNavLevel = (typeof HMI_NAV_LEVELS)[keyof typeof HMI_NAV_LEVELS];

// ---------------------------------------------------------------------------
// Title bar button catalog (standard buttons in 1001_ScreenLayout title bar)
// ---------------------------------------------------------------------------

export interface HmiTitleBarButton {
  name: string;
  action: string;
  icon: string;
}

export const HMI_TITLE_BAR_BUTTONS: Record<string, HmiTitleBarButton> = {
  HOME: { name: "Home", action: "NavigateToStartScreen", icon: "house" },
  PREVIOUS: { name: "Previous", action: "NavigatePrev", icon: "arrow-left" },
  LEVEL_UP: { name: "LevelUp", action: "NavigateUp", icon: "arrow-up" },
  NEXT: { name: "Next", action: "NavigateNext", icon: "arrow-right" },
  MENU: { name: "Menu", action: "Navigation.ShowMainNavigation", icon: "hamburger" },
};

// ---------------------------------------------------------------------------
// PLC-side tag contracts the Template Suite expects
// Pac-Forge must either generate these tags in the PLC, or map existing project
// tags to these names during the HMI generation step.
// ---------------------------------------------------------------------------

export interface HmiTemplateTag {
  name: string;
  type: string;
  description: string;
  isSystemVariable?: boolean;
  values?: Record<number, string>;
}

export const HMI_TEMPLATE_TAGS: Record<string, HmiTemplateTag> = {
  CURRENT_MACHINE_STATE: {
    name: "CurrentMachineState",
    type: "Int",
    description: "Drives machine state icon + text in status bar",
    values: {
      0: "Undefined",
      1: "Production",
      2: "Startup",
      3: "Paused",
      4: "Shutdown",
      5: "Stopped",
    },
  },
  USER_NAME: {
    name: "@UserName",
    type: "WString",
    description: "Currently logged-in user — WinCC Unified system variable",
    isSystemVariable: true,
  },
};

// ---------------------------------------------------------------------------
// Text lists referenced by the Template Suite
// ---------------------------------------------------------------------------

export const HMI_TEMPLATE_TEXT_LISTS = {
  /** Int → state text (e.g. 1 → "Production"). Bound to CurrentMachineState. */
  MACHINE_STATE: "MachineState",
  /** Int → graphics reference (light theme). */
  MACHINE_STATE_LIGHT: "MachineState_Light",
  /** Int → graphics reference (dark theme). */
  MACHINE_STATE_DARK: "MachineState_Dark",
} as const;

// ---------------------------------------------------------------------------
// Design framework — fonts, grid, color tokens
// ---------------------------------------------------------------------------

export const HMI_TEMPLATE_DESIGN = {
  FONT_FAMILY: "Siemens Sans",
  TITLE_BAR_FONT_PT: 18,
  TITLE_BAR_FONT_STYLE: "Bold",
  /** 8-pixel grid framework from V6.0 Section 3.3. */
  GRID_PX: 8,
} as const;

/**
 * Color palette tokens — resolve against the selected theme (SiemensLight / SiemensDark / DeepBlue)
 * at generation time. Token names match the Template Suite's design tokens.
 */
export const HMI_TEMPLATE_COLOR_TOKENS = {
  TITLE_BAR_BG: "Basic 80",
  STATUS_BAR_BG: "Basic 10",
  MAIN_WINDOW_BG: "Basic 40",
  SUB_NAV_BG: "Basic 60",
  BUTTON_ACCENT: "Accent 1",
  BUTTON_TEXT: "Basic 0",
} as const;

// ---------------------------------------------------------------------------
// Layout zone rectangles — proportional hints
// ---------------------------------------------------------------------------

export interface LayoutZoneRect {
  top: number;
  left: number;
  width: number;
  height: number;
}

/**
 * Percent-based proportions for layout zones when all nav levels are visible.
 * Derived from V6.0 manual Figure 4-9 and the preconfigured 1001_ScreenLayout panels.
 * Values are percentages of the panel's native resolution.
 */
export const HMI_TEMPLATE_LAYOUT_PERCENT: Record<HmiLayoutZone, LayoutZoneRect> = {
  titleBar:       { top: 0,   left: 0,  width: 100, height: 6 },
  statusBar:      { top: 6,   left: 0,  width: 100, height: 4 },
  mainWindow:     { top: 10,  left: 0,  width: 100, height: 84 },
  mainNavigation: { top: 6,   left: 80, width: 20,  height: 88 },
  subNavigation:  { top: 94,  left: 0,  width: 100, height: 6 },
  thirdLevelNav:  { top: 10,  left: 0,  width: 15,  height: 84 },
  tabNav:         { top: 10,  left: 0,  width: 100, height: 4 },
};

/**
 * Compute the absolute pixel rect of a layout zone for a given panel.
 * Handles the 8-pixel grid snap documented in Section 3.3.
 */
export function getZoneRect(
  zone: HmiLayoutZone,
  panel: HmiPanelConfig,
): { x: number; y: number; width: number; height: number } {
  const pct = HMI_TEMPLATE_LAYOUT_PERCENT[zone];
  const grid = HMI_TEMPLATE_DESIGN.GRID_PX;

  const rawX = (pct.left / 100) * panel.screenWidth;
  const rawY = (pct.top / 100) * panel.screenHeight;
  const rawW = (pct.width / 100) * panel.screenWidth;
  const rawH = (pct.height / 100) * panel.screenHeight;

  return {
    x: Math.round(rawX / grid) * grid,
    y: Math.round(rawY / grid) * grid,
    width: Math.round(rawW / grid) * grid,
    height: Math.round(rawH / grid) * grid,
  };
}

/**
 * Compute the MainWindow rect after subtracting visible navigation levels.
 * Pac-Forge generated content should fit inside this rect.
 */
export function getContentRect(
  panel: HmiPanelConfig,
  visibleNavLevels: Set<HmiNavLevel>,
): { x: number; y: number; width: number; height: number } {
  const mainWindow = getZoneRect(HMI_LAYOUT_ZONES.MAIN_WINDOW, panel);
  let { x, y, width, height } = mainWindow;

  if (visibleNavLevels.has(HMI_NAV_LEVELS.SUB)) {
    const sub = getZoneRect(HMI_LAYOUT_ZONES.SUB_NAVIGATION, panel);
    height -= sub.height;
  }
  if (visibleNavLevels.has(HMI_NAV_LEVELS.THIRD)) {
    const third = getZoneRect(HMI_LAYOUT_ZONES.THIRD_LEVEL_NAV, panel);
    x += third.width;
    width -= third.width;
  }
  if (visibleNavLevels.has(HMI_NAV_LEVELS.TAB)) {
    const tab = getZoneRect(HMI_LAYOUT_ZONES.TAB_NAV, panel);
    y += tab.height;
    height -= tab.height;
  }

  return { x, y, width, height };
}

// ---------------------------------------------------------------------------
// Folder paths inside the Template Suite library
// Used when the wizard copies master copies or when the bridge enumerates items.
// ---------------------------------------------------------------------------

export const HMI_TEMPLATE_LIBRARY_PATHS = {
  /** Root library name (Light variant). */
  LIGHT_ROOT: "HMI Template Suite Light (WinCC Unified)_V20",
  /** Root library name (Dark variant). */
  DARK_ROOT: "HMI Template Suite Dark (WinCC Unified)_V20",
  /** Types folder holds the 3 Template Suite faceplate types. */
  TYPES: "Types",
  /** Master copies hold the preconfigured panels, layouts, and templates. */
  MASTER_COPIES: "Master copies",
  /** Top-level folder inside Master copies. */
  HMI_TEMPLATE_SUITE: "HMI Template Suite",
  /** Panel family container (WinCC Unified vs View of Things). */
  WINCC_UNIFIED: "WinCC Unified",
  /** Sub-folder per resolution. */
  RESOLUTION_FOLDERS: {
    R800x480: "02 - 800 x 480",
    R1280x800: "03 - 1280 x 800",
    R1366x768: "04 - 1366 x 768",
    R1920x1080: "05 - 1920 x 1080",
  },
  /** Sub-folder per content type inside each resolution folder. */
  CONTENT_FOLDERS: {
    DEVICE: "00 - Device",
    SCREEN_LAYOUT: "01 - Screen layout",
    SCREENS: "02 - Screens",
    POPUP_SCREENS: "03 - Popup screens",
    OTHER_TEMPLATES: "04 - Other Templates",
  },
} as const;

/**
 * Resolve the Template Suite library root path for a given theme.
 */
export function getLibraryRoot(theme: "SiemensLight" | "SiemensDark" | "DeepBlue"): string {
  // DeepBlue is a palette within the Dark library (per V6.0 manual Section 3.2.5)
  if (theme === "SiemensDark" || theme === "DeepBlue") {
    return HMI_TEMPLATE_LIBRARY_PATHS.DARK_ROOT;
  }
  return HMI_TEMPLATE_LIBRARY_PATHS.LIGHT_ROOT;
}
