/**
 * plcsim-test-report.ts
 *
 * Professional PDF report generator for PLCSIM test results.
 * Uses jspdf + jspdf-autotable for table rendering.
 */

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type {
  PlcsimTestSuite,
  TestCaseResult,
} from "@/types/plcsim-test";

// ---------------------------------------------------------------------------
// Brand colours (Pac Technologies)
// ---------------------------------------------------------------------------

const BRAND = {
  primary: [30, 64, 175] as [number, number, number],     // blue-700
  primaryLight: [59, 130, 246] as [number, number, number], // blue-500
  dark: [15, 23, 42] as [number, number, number],           // slate-900
  text: [30, 41, 59] as [number, number, number],           // slate-800
  muted: [100, 116, 139] as [number, number, number],       // slate-500
  success: [22, 163, 74] as [number, number, number],       // green-600
  fail: [220, 38, 38] as [number, number, number],          // red-600
  warn: [217, 119, 6] as [number, number, number],          // amber-600
  white: [255, 255, 255] as [number, number, number],
  tableHeader: [241, 245, 249] as [number, number, number], // slate-100
  tableStripe: [248, 250, 252] as [number, number, number], // slate-50
};

// ---------------------------------------------------------------------------
// Interfaces
// ---------------------------------------------------------------------------

export interface TestReportOptions {
  projectName: string;
  projectDescription?: string;
  plcType?: string;
  engineerName?: string;
  /** Base64 PNG/JPEG logo (data:image/... or raw base64) */
  logoBase64?: string;
  companyName?: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function statusColor(status: string): [number, number, number] {
  switch (status) {
    case "pass": return BRAND.success;
    case "fail": return BRAND.fail;
    case "error": return BRAND.warn;
    default: return BRAND.muted;
  }
}

function statusLabel(status: string): string {
  switch (status) {
    case "pass": return "PASS";
    case "fail": return "FAIL";
    case "error": return "ERROR";
    case "skipped": return "SKIPPED";
    default: return status.toUpperCase();
  }
}

function formatDate(iso: string | null): string {
  if (!iso) return "—";
  return new Date(iso).toLocaleString("en-GB", {
    day: "2-digit", month: "short", year: "numeric",
    hour: "2-digit", minute: "2-digit",
  });
}

// ---------------------------------------------------------------------------
// PDF Generator
// ---------------------------------------------------------------------------

export function generateTestReport(
  suite: PlcsimTestSuite,
  options: TestReportOptions,
): jsPDF {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // ---- Header band ----
  doc.setFillColor(...BRAND.dark);
  doc.rect(0, 0, pageWidth, 38, "F");

  // Logo (if provided)
  if (options.logoBase64) {
    try {
      const logoData = options.logoBase64.startsWith("data:")
        ? options.logoBase64
        : `data:image/png;base64,${options.logoBase64}`;
      doc.addImage(logoData, "PNG", margin, 6, 26, 26);
    } catch {
      // Logo failed to load — skip
    }
  }

  // Title
  const titleX = options.logoBase64 ? margin + 30 : margin;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...BRAND.white);
  doc.text("PLC Test Report", titleX, 16);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(180, 190, 210);
  doc.text(options.projectName, titleX, 23);

  if (options.companyName) {
    doc.setFontSize(8);
    doc.text(options.companyName, titleX, 29);
  }

  // Date on right side
  doc.setFontSize(8);
  doc.setTextColor(180, 190, 210);
  const dateStr = formatDate(new Date().toISOString());
  doc.text(dateStr, pageWidth - margin, 16, { align: "right" });
  doc.text(`Generated by Pac-Forge`, pageWidth - margin, 22, { align: "right" });

  y = 46;

  // ---- Project details ----
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...BRAND.text);
  doc.text("Project Details", margin, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...BRAND.muted);

  const details: [string, string][] = [
    ["Project", options.projectName],
    ...(options.projectDescription ? [["Description", options.projectDescription] as [string, string]] : []),
    ...(options.plcType ? [["PLC Type", options.plcType] as [string, string]] : []),
    ...(options.engineerName ? [["Engineer", options.engineerName] as [string, string]] : []),
    ["Test Date", suite.lastRunAt ? formatDate(suite.lastRunAt) : formatDate(suite.generatedAt)],
    ["Total Tests", String(suite.testCases.filter((t) => t.approved).length)],
  ];

  for (const [label, value] of details) {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...BRAND.text);
    doc.text(`${label}:`, margin, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...BRAND.muted);
    doc.text(value, margin + 30, y);
    y += 5;
  }

  y += 4;

  // ---- Summary box ----
  if (suite.summary) {
    const s = suite.summary;
    const boxH = 18;
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(margin, y, contentWidth, boxH, 2, 2, "F");

    const cols = [
      { label: "Total", value: String(s.total), color: BRAND.text },
      { label: "Passed", value: String(s.passed), color: BRAND.success },
      { label: "Failed", value: String(s.failed), color: BRAND.fail },
      { label: "Errors", value: String(s.errors), color: BRAND.warn },
      { label: "Skipped", value: String(s.skipped), color: BRAND.muted },
    ];
    const colW = contentWidth / cols.length;
    for (let i = 0; i < cols.length; i++) {
      const cx = margin + colW * i + colW / 2;
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...cols[i].color);
      doc.text(cols[i].value, cx, y + 9, { align: "center" });
      doc.setFontSize(7);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...BRAND.muted);
      doc.text(cols[i].label, cx, y + 14, { align: "center" });
    }

    y += boxH + 8;
  }

  // ---- Test Results Table ----
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...BRAND.text);
  doc.text("Test Results", margin, y);
  y += 2;

  // Build result lookup
  const resultMap = new Map<string, TestCaseResult>();
  for (const r of suite.results) {
    resultMap.set(r.testCaseId, r);
  }

  const approvedTests = suite.testCases.filter((tc) => tc.approved);

  const tableBody = approvedTests.map((tc) => {
    const result = resultMap.get(tc.id);
    return [
      tc.name,
      tc.category.toUpperCase(),
      tc.sequenceName ?? "—",
      `${tc.steps.length}`,
      result ? statusLabel(result.status) : "NOT RUN",
      result?.runMode === "manual" ? "Manual" : result ? "Auto" : "—",
      result?.comment?.split("\n")[0]?.slice(0, 50) ?? "—",
    ];
  });

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [["Test Name", "Category", "Sequence", "Steps", "Result", "Mode", "Comment"]],
    body: tableBody,
    styles: {
      fontSize: 8,
      cellPadding: 2,
      textColor: BRAND.text,
      lineColor: [226, 232, 240],
      lineWidth: 0.1,
    },
    headStyles: {
      fillColor: BRAND.primary,
      textColor: BRAND.white,
      fontStyle: "bold",
      fontSize: 8,
    },
    alternateRowStyles: {
      fillColor: BRAND.tableStripe,
    },
    columnStyles: {
      0: { cellWidth: 45 },
      4: { fontStyle: "bold", halign: "center" },
      5: { halign: "center" },
    },
    didParseCell: (data) => {
      // Colour the Result column based on status
      if (data.section === "body" && data.column.index === 4) {
        const val = String(data.cell.raw);
        if (val === "PASS") data.cell.styles.textColor = BRAND.success;
        else if (val === "FAIL") data.cell.styles.textColor = BRAND.fail;
        else if (val === "ERROR") data.cell.styles.textColor = BRAND.warn;
        else data.cell.styles.textColor = BRAND.muted;
      }
    },
  });

  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;

  // ---- Detailed results per test ----
  for (const tc of approvedTests) {
    const result = resultMap.get(tc.id);
    if (!result) continue;

    // Check if we need a new page (at least 40mm needed)
    if (y > doc.internal.pageSize.getHeight() - 50) {
      doc.addPage();
      y = margin;
    }

    // Test header
    doc.setFillColor(...statusColor(result.status));
    doc.rect(margin, y, 3, 6, "F");
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...BRAND.text);
    doc.text(tc.name, margin + 5, y + 4.5);

    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...statusColor(result.status));
    const statusText = `${statusLabel(result.status)} (${result.runMode})`;
    doc.text(statusText, pageWidth - margin, y + 4.5, { align: "right" });

    y += 9;

    // Description
    if (tc.description) {
      doc.setFontSize(8);
      doc.setTextColor(...BRAND.muted);
      doc.text(tc.description, margin + 5, y);
      y += 5;
    }

    // Step results table
    if (result.stepResults.length > 0) {
      const stepBody = result.stepResults.map((sr) => {
        const assertSummary = sr.assertions.length > 0
          ? sr.assertions
              .map((a) => `${a.tag}: ${a.passed ? "✓" : "✗"} (exp=${a.expected}, act=${a.actual ?? "null"})`)
              .join("; ")
          : "—";
        return [
          `${sr.stepNumber}`,
          statusLabel(sr.status),
          `${sr.durationMs}ms`,
          assertSummary.slice(0, 80),
          sr.errorMessage?.slice(0, 40) ?? "—",
        ];
      });

      autoTable(doc, {
        startY: y,
        margin: { left: margin + 5, right: margin },
        head: [["Step", "Result", "Duration", "Assertions", "Error"]],
        body: stepBody,
        styles: {
          fontSize: 7,
          cellPadding: 1.5,
          textColor: BRAND.text,
          lineColor: [226, 232, 240],
          lineWidth: 0.1,
        },
        headStyles: {
          fillColor: BRAND.tableHeader,
          textColor: BRAND.text,
          fontStyle: "bold",
          fontSize: 7,
        },
        columnStyles: {
          0: { cellWidth: 10, halign: "center" },
          1: { cellWidth: 14, halign: "center" },
          2: { cellWidth: 16, halign: "right" },
        },
        didParseCell: (data) => {
          if (data.section === "body" && data.column.index === 1) {
            const val = String(data.cell.raw);
            if (val === "PASS") data.cell.styles.textColor = BRAND.success;
            else if (val === "FAIL") data.cell.styles.textColor = BRAND.fail;
            else data.cell.styles.textColor = BRAND.warn;
          }
        },
      });

      y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 3;
    }

    // Comment
    if (result.comment) {
      doc.setFontSize(7);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(...BRAND.muted);
      const commentLines = doc.splitTextToSize(`Notes: ${result.comment}`, contentWidth - 10);
      doc.text(commentLines, margin + 5, y);
      y += commentLines.length * 3.5 + 2;
    }

    // PLC State Snapshots (from failed steps)
    for (const sr of result.stepResults) {
      if (!sr.snapshot || sr.snapshot.tags.length === 0) continue;

      if (y > doc.internal.pageSize.getHeight() - 40) {
        doc.addPage();
        y = margin;
      }

      doc.setFontSize(7);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...BRAND.warn);
      doc.text(`PLC State Snapshot (Step ${sr.stepNumber} — ${sr.status.toUpperCase()})`, margin + 5, y);
      y += 3;

      const snapBody = sr.snapshot.tags.map((t) => [
        t.tag,
        t.value === null ? "null" : String(t.value),
        t.dataType,
      ]);

      autoTable(doc, {
        startY: y,
        margin: { left: margin + 5, right: margin },
        head: [["Tag", "Value", "Type"]],
        body: snapBody,
        styles: {
          fontSize: 6,
          cellPadding: 1,
          textColor: BRAND.text,
          lineColor: [226, 232, 240],
          lineWidth: 0.1,
        },
        headStyles: {
          fillColor: [254, 243, 199], // amber-100
          textColor: BRAND.warn,
          fontStyle: "bold",
          fontSize: 6,
        },
        columnStyles: {
          0: { cellWidth: 70, fontStyle: "bold" },
          2: { cellWidth: 15 },
        },
      });

      y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 3;
    }

    y += 4;
  }

  // ---- Footer / signature ----
  // Ensure we're on a page with space
  if (y > doc.internal.pageSize.getHeight() - 40) {
    doc.addPage();
    y = margin;
  }

  y += 10;
  doc.setDrawColor(200, 210, 220);
  doc.line(margin, y, margin + 70, y);
  y += 5;
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...BRAND.muted);
  doc.text("Engineer Signature", margin, y);

  doc.line(pageWidth - margin - 70, y - 5, pageWidth - margin, y - 5);
  doc.text("Date", pageWidth - margin - 70, y);

  // Page numbers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(...BRAND.muted);
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 8,
      { align: "center" },
    );
  }

  return doc;
}

/**
 * Generate and trigger download of the test report PDF.
 */
export function downloadTestReport(
  suite: PlcsimTestSuite,
  options: TestReportOptions,
): void {
  const doc = generateTestReport(suite, options);
  const filename = `${options.projectName.replace(/[^a-zA-Z0-9]/g, "_")}_Test_Report_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
