// gen-tags.mjs — generate tags.mjs (the dashboard's IO register) from a
// Pac-Forge bridge /tia/extract-project JSON dump.
//   node gen-tags.mjs <extract.json>
// Classification: %I+Bool → di, %Q+Bool → do, other %I → ai, other %Q → ao.
// Memory flags (%M) and unaddressed tags are skipped — the Watch tab covers those.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const src = process.argv[2];
if (!src) { console.error("usage: node gen-tags.mjs <extract.json>"); process.exit(1); }
const raw = JSON.parse(fs.readFileSync(src, "utf8").replace(/^﻿/, "")); // PS Out-File writes a BOM
const pick = (o, ...keys) => { for (const k of keys) if (o?.[k] != null) return o[k]; return null; };

const tables = pick(raw, "tag_tables", "TagTables", "tagTables") ?? [];
const out = [];
for (const tbl of tables) {
  const tblName = pick(tbl, "name", "Name") ?? "?";
  for (const t of pick(tbl, "tags", "Tags") ?? []) {
    const name = pick(t, "name", "Name");
    const addr = (pick(t, "address", "Address") ?? "").trim();
    const type = pick(t, "data_type", "DataType", "dataType") ?? "";
    const comment = pick(t, "comment", "Comment") ?? "";
    if (!name || !/^%[IQ]/i.test(addr)) continue; // IO only — no %M, no constants
    if (type.startsWith('"')) continue; // UDT-typed (safety telegrams etc.) — FW 2.9 Web API can't read structs
    const isBool = /^bool$/i.test(type);
    const isInput = /^%I/i.test(addr);
    const kind = isBool ? (isInput ? "di" : "do") : (isInput ? "ai" : "ao");
    out.push({ name, addr, type, comment, table: tblName, kind });
  }
}
// stable order: table, then numeric address order
const addrKey = (a) => { const m = a.match(/(\d+)(?:\.(\d+))?/); return m ? Number(m[1]) * 100 + Number(m[2] ?? 0) : 1e9; };
out.sort((a, b) => a.table.localeCompare(b.table) || addrKey(a.addr) - addrKey(b.addr));

const project = {
  name: pick(raw, "project_name", "ProjectName") ?? "CVL-2129-5002001 6.8",
  cpu: "CPU 1511F-1 PN (FW V2.9)",
};
const counts = out.reduce((m, t) => ((m[t.kind] = (m[t.kind] ?? 0) + 1), m), {});
const dest = path.join(path.dirname(fileURLToPath(import.meta.url)), "tags.mjs");
fs.writeFileSync(dest,
  `// tags.mjs — GENERATED by gen-tags.mjs from a bridge /tia/extract-project dump.\n` +
  `// Do not hand-edit; regenerate against the TIA project instead.\n` +
  `// ${new Date().toISOString()} — ${out.length} IO tags (${Object.entries(counts).map(([k, v]) => `${k}:${v}`).join(", ")})\n` +
  `export const PROJECT = ${JSON.stringify(project, null, 2)};\n` +
  `export const IO_TAGS = ${JSON.stringify(out, null, 1)};\n`);
console.log(`tags.mjs written: ${out.length} IO tags (${Object.entries(counts).map(([k, v]) => `${k}:${v}`).join(", ")}) from ${tables.length} tables`);
