// tags.mjs — GENERATED by gen-tags.mjs from a bridge /tia/extract-project dump.
// Do not hand-edit; regenerate against the TIA project instead.
// 2026-07-21T06:57:58.386Z — 391 IO tags (do:35, di:134, ao:110, ai:112)
export const PROJECT = {
  "name": "CVL-2129-5002001 6.8",
  "cpu": "CPU 1511F-1 PN (FW V2.9)"
};
export const IO_TAGS = [
 {
  "name": "=GND+CB8-H.001",
  "addr": "%Q247.0",
  "type": "Bool",
  "comment": "Dimensioner Light Tower Red Infeed",
  "table": "Default tag table",
  "kind": "do"
 },
 {
  "name": "=GND+CB8-H.002",
  "addr": "%Q247.1",
  "type": "Bool",
  "comment": "Dimensioner Light Tower Yellow infeed",
  "table": "Default tag table",
  "kind": "do"
 },
 {
  "name": "=GND+CB8-H.003",
  "addr": "%Q247.2",
  "type": "Bool",
  "comment": "Dimensioner Light Tower Green Infeed",
  "table": "Default tag table",
  "kind": "do"
 },
 {
  "name": "=GND+C3B-H.001",
  "addr": "%Q247.4",
  "type": "Bool",
  "comment": "Dimensioner Light Tower Red Outfeed",
  "table": "Default tag table",
  "kind": "do"
 },
 {
  "name": "=PR10_1+CR-M1",
  "addr": "%Q247.5",
  "type": "Bool",
  "comment": "Elevator 1 Actuator 1",
  "table": "Default tag table",
  "kind": "do"
 },
 {
  "name": "=GND+C3B-H.002",
  "addr": "%Q247.6",
  "type": "Bool",
  "comment": "Dimensioner Light Tower Yellow Outfeed",
  "table": "Default tag table",
  "kind": "do"
 },
 {
  "name": "=PR10_2+CR-M1",
  "addr": "%Q247.7",
  "type": "Bool",
  "comment": "Elevator 2 Actuator 1",
  "table": "Default tag table",
  "kind": "do"
 },
 {
  "name": "=GND+C3B-H.003",
  "addr": "%Q248.0",
  "type": "Bool",
  "comment": "Dimensioner Light Tower Green Outfeed",
  "table": "Default tag table",
  "kind": "do"
 },
 {
  "name": "=GND+C2B-Q.001",
  "addr": "%Q255.4",
  "type": "Bool",
  "comment": "Roller Door Open Outfeed",
  "table": "Default tag table",
  "kind": "do"
 },
 {
  "name": "=GND+C2B-Q.002",
  "addr": "%Q255.5",
  "type": "Bool",
  "comment": "Roller Door Close Outfeed",
  "table": "Default tag table",
  "kind": "do"
 },
 {
  "name": "=GND+CB8-Q.001",
  "addr": "%Q255.6",
  "type": "Bool",
  "comment": "Roller Door Open Infeed",
  "table": "Default tag table",
  "kind": "do"
 },
 {
  "name": "=GND+CB8-Q.002",
  "addr": "%Q255.7",
  "type": "Bool",
  "comment": "Roller Door Close Infeed",
  "table": "Default tag table",
  "kind": "do"
 },
 {
  "name": "=PR10_1+BR1",
  "addr": "%Q742.4",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "do"
 },
 {
  "name": "=PR10_1+BR2",
  "addr": "%Q742.5",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "do"
 },
 {
  "name": "=PR10_2+BR1",
  "addr": "%Q742.6",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "do"
 },
 {
  "name": "=PR10_2+BR2",
  "addr": "%Q742.7",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "do"
 },
 {
  "name": "=PR10-BR1_FB.001",
  "addr": "%I776.2",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=PR10-BR1_FB.002",
  "addr": "%I776.3",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=PR10-BR2_FB.001",
  "addr": "%I776.4",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=PR10-BR2_FB.002",
  "addr": "%I776.5",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=GND+CB6-SEN.002",
  "addr": "%I778.0",
  "type": "Bool",
  "comment": "GND Conveyor Bed 6 Diag Sensor",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=GND+CB9-SEN.001",
  "addr": "%I778.4",
  "type": "Bool",
  "comment": "GND Conveyor Bed 9 Sensor 1",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=GND+CB6-PX.001",
  "addr": "%I778.5",
  "type": "Bool",
  "comment": "GND Conveyor Bed Cam Up",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=GND+CB6-PX.002",
  "addr": "%I778.6",
  "type": "Bool",
  "comment": "GND Conveyor Bed 6 Cam Down",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=GND+CB5-SEN.001",
  "addr": "%I778.7",
  "type": "Bool",
  "comment": "GND Conveyor Bed 5 Sensor 1",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "Tag_9",
  "addr": "%I779.0",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=GND+CB8-SEN.002",
  "addr": "%I779.1",
  "type": "Bool",
  "comment": "GND Dimensioner Height",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=GND+CB6-SEN.003",
  "addr": "%I779.2",
  "type": "Bool",
  "comment": "GND Conveyor Bed 6 Sensor 3 (Spare)",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=GND+CB8-LC.001",
  "addr": "%I779.3",
  "type": "Bool",
  "comment": "GND Dimensioner Light Curtain",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "Tag_13",
  "addr": "%I779.4",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "Tag_14",
  "addr": "%I779.5",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "Tag_15",
  "addr": "%I779.6",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=GND+CB4+SEN.001",
  "addr": "%I779.7",
  "type": "Bool",
  "comment": "GND Conveyor Bed 4 Sensor 001",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=GND+CB8-SEN.007",
  "addr": "%I782.4",
  "type": "Bool",
  "comment": "Roller Door Open",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=GND+CB8-SEN.006",
  "addr": "%I782.5",
  "type": "Bool",
  "comment": "Roller Door Closed",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=ELV1+CR-SEN.002",
  "addr": "%I792.6",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=GND+CB12-SEN.001",
  "addr": "%I793.0",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=MCC+ELVA-SEN.001",
  "addr": "%I793.1",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=MCC+ELVA-SEN.002",
  "addr": "%I793.2",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=MCC+ELVB-SEN.001",
  "addr": "%I793.3",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=MCC+ELVB-SEN.002",
  "addr": "%I793.4",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=GND+C2B-SEN.001",
  "addr": "%I793.5",
  "type": "Bool",
  "comment": "Roller Door Open Pos Outfeed",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=GND+C2B-SEN.002",
  "addr": "%I793.6",
  "type": "Bool",
  "comment": "Roller Door Close Pos Outfeed",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=LVL1+HC2-SEN.002",
  "addr": "%I794.0",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "Tag_3",
  "addr": "%I794.2",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=LVL1+HC2-SEN.004",
  "addr": "%I794.3",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "Tag_5",
  "addr": "%I794.4",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=LVL8+HC2-SEN.001",
  "addr": "%I795.2",
  "type": "Bool",
  "comment": "Level 8 Handover Conveyor 2 Sensor 1",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=GND+CB9-PB.001",
  "addr": "%I795.4",
  "type": "Bool",
  "comment": "Infeed Reset Pushbutton",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=GND+CB3-PB.001",
  "addr": "%I795.5",
  "type": "Bool",
  "comment": "Outfeed Reset Pushbutton",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "MOVU_IN_Estop",
  "addr": "%I1240.0",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "MOVU_OUT_ESTOP",
  "addr": "%Q1240.0",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "do"
 },
 {
  "name": "MOVU_IN_AccessGranted",
  "addr": "%I1240.1",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "MOVE_OUT_PermitierClosed",
  "addr": "%Q1240.1",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "do"
 },
 {
  "name": "MOVU_IN_PermititerClosed",
  "addr": "%I1240.2",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "MOVU_OUT_AutoMode",
  "addr": "%Q1240.2",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "do"
 },
 {
  "name": "MOVU_IN_AutoMode",
  "addr": "%I1240.3",
  "type": "Bool",
  "comment": "",
  "table": "Default tag table",
  "kind": "di"
 },
 {
  "name": "=GND+CB8-SEN.003",
  "addr": "%I778.1",
  "type": "Bool",
  "comment": "GND Dimensioner Width Left",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=GND+CB8-SEN.004",
  "addr": "%I778.2",
  "type": "Bool",
  "comment": "GND Dimensioner Width Right",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=GND+CB6-SEN.001",
  "addr": "%I778.3",
  "type": "Bool",
  "comment": "GND Conveyor Bed 6 Transfer Entry",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=GND+CB1-SEN.002",
  "addr": "%I780.1",
  "type": "Bool",
  "comment": "GND Conveyor Bed 1 Sensor 2",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=GND+CB1-PX.001",
  "addr": "%I780.2",
  "type": "Bool",
  "comment": "GND Conveyor Bed 1 Cam Up",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=GND+CB1-SEN.003",
  "addr": "%I780.3",
  "type": "Bool",
  "comment": "GND Conveyor Bed 1 Sensor 3 (Spare)",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_2+BC-B1",
  "addr": "%I780.4",
  "type": "Bool",
  "comment": "Elevator 2 Reference Position",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_2+BC-S1",
  "addr": "%I780.5",
  "type": "Bool",
  "comment": "Elevator 2 Bottom Limit Switch 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_2+BC-S2",
  "addr": "%I780.6",
  "type": "Bool",
  "comment": "Elevator 2 Bottom Limit Switch 2",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=GND+CB2-SEN.001",
  "addr": "%I780.7",
  "type": "Bool",
  "comment": "GND Conveyor Bed 2 Sensor 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=GND+CB3-SEN.001",
  "addr": "%I781.0",
  "type": "Bool",
  "comment": "GND Conveyor Bed 3 Sensor 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=GND+CB4-SEN.001",
  "addr": "%I781.1",
  "type": "Bool",
  "comment": "GND Conveyor Bed 4 Sensor 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_1+BC-B1",
  "addr": "%I781.3",
  "type": "Bool",
  "comment": "Elevator 1 Reference Position",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_1+BC-S1",
  "addr": "%I781.4",
  "type": "Bool",
  "comment": "Elevator 1 Bottom Limit Switch 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_1+BC-S2",
  "addr": "%I781.5",
  "type": "Bool",
  "comment": "Elevator 1 Bottom Limit Switch 2",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=GND+CB7-SEN.001",
  "addr": "%I781.6",
  "type": "Bool",
  "comment": "GND Conveyor Bed 7 Sensor 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=GND+CB8-SEN.001",
  "addr": "%I781.7",
  "type": "Bool",
  "comment": "GND Conveyor Bed 8 Sensor 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=GND+CB8-SEN.005",
  "addr": "%I782.3",
  "type": "Bool",
  "comment": "GND Dimensioner Sensor 4",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=GND+CB4-SEN.002",
  "addr": "%I782.7",
  "type": "Bool",
  "comment": "",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL1+HC1-PX.003",
  "addr": "%I783.1",
  "type": "Bool",
  "comment": "Turn Table Paddle Stop Shaft Straight B",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=GND+CB0-PX.001",
  "addr": "%I784.0",
  "type": "Bool",
  "comment": "",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=GND+CB1-PX.002",
  "addr": "%I784.1",
  "type": "Bool",
  "comment": "GND Conveyor Bed 1 Cam Down",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL1+HC1-SEN.001",
  "addr": "%I784.2",
  "type": "Bool",
  "comment": "Level 1 Handover Conveyor 1 Sensor 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL2+HC1-SEN.001",
  "addr": "%I784.3",
  "type": "Bool",
  "comment": "Level 2 Handover Conveyor 1 Sensor 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL3+HC1-SEN.001",
  "addr": "%I784.4",
  "type": "Bool",
  "comment": "Level 3 Handover Conveyor 1 Sensor 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL4+HC1-SEN.001",
  "addr": "%I784.5",
  "type": "Bool",
  "comment": "Level 4 Handover Conveyor 1 Sensor 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL5+HC1-SEN.001",
  "addr": "%I784.6",
  "type": "Bool",
  "comment": "Level 5 Handover Conveyor 1 Sensor 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL6+HC1-SEN.001",
  "addr": "%I784.7",
  "type": "Bool",
  "comment": "Level 6 Handover Conveyor 1 Sensor 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL7+HC1-SEN.001",
  "addr": "%I785.0",
  "type": "Bool",
  "comment": "Level 7 Handover Conveyor 1 Sensor 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL8+HC1-SEN.001",
  "addr": "%I785.1",
  "type": "Bool",
  "comment": "Level 8 Handover Conveyor 1 Sensor 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL9+HC1-SEN.001",
  "addr": "%I785.2",
  "type": "Bool",
  "comment": "Level 9 Handover Conveyor 1 Sensor 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL1+HC2-SEN.001",
  "addr": "%I785.3",
  "type": "Bool",
  "comment": "Level 1 Handover Conveyor 1 Sensor 2",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL2+HC2-SEN.001",
  "addr": "%I785.4",
  "type": "Bool",
  "comment": "Level 2 Handover Conveyor 1 Sensor 2",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL3+HC2-SEN.001",
  "addr": "%I785.5",
  "type": "Bool",
  "comment": "Level 3 Handover Conveyor 1 Sensor 2",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL4+HC2-SEN.001",
  "addr": "%I785.6",
  "type": "Bool",
  "comment": "Level 4 Handover Conveyor 1 Sensor 2",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL5+HC2-SEN.001",
  "addr": "%I785.7",
  "type": "Bool",
  "comment": "Level 5 Handover Conveyor 2 Sensor 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL6+HC2-SEN.001",
  "addr": "%I786.0",
  "type": "Bool",
  "comment": "Level 6 Handover Conveyor 2 Sensor 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL7+HC2-SEN.001",
  "addr": "%I786.1",
  "type": "Bool",
  "comment": "Level 7 Handover Conveyor 2 Sensor 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL9+HC2-SEN.001",
  "addr": "%I786.3",
  "type": "Bool",
  "comment": "Level 9 Handover Conveyor 2 Sensor 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_1+CR-B1",
  "addr": "%I786.4",
  "type": "Bool",
  "comment": "Carrier Chain 1 OK",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_1+CR-B2",
  "addr": "%I786.5",
  "type": "Bool",
  "comment": "Mechanical Locking Device 1 Retracted",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_1+CR-B3",
  "addr": "%I786.6",
  "type": "Bool",
  "comment": "Carrier Chain 2 OK",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_1+CR-B4",
  "addr": "%I786.7",
  "type": "Bool",
  "comment": "Mechanical Locking Device 2 Retracted",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_1+CR-B5",
  "addr": "%I787.0",
  "type": "Bool",
  "comment": "Carrier Chain 3 OK",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_1+CR-B6",
  "addr": "%I787.1",
  "type": "Bool",
  "comment": "Mechanical Locking Device 3 Retracted",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_1+CR-B7",
  "addr": "%I787.2",
  "type": "Bool",
  "comment": "Carrier Chain 4 OK",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_1+CR-B8",
  "addr": "%I787.3",
  "type": "Bool",
  "comment": "Mechanical Locking Device 4 Retracted",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_1+CR-B9",
  "addr": "%I787.4",
  "type": "Bool",
  "comment": "Detection Carrier Infeed/Outfeed Position",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_2+CR-B1",
  "addr": "%I788.1",
  "type": "Bool",
  "comment": "Carrier Chain 1 OK",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_2+CR-B2",
  "addr": "%I788.2",
  "type": "Bool",
  "comment": "Mechanical Locking Device 1 Retracted",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_2+CR-B3",
  "addr": "%I788.3",
  "type": "Bool",
  "comment": "Carrier Chain 2 OK",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_2+C4-B4",
  "addr": "%I788.4",
  "type": "Bool",
  "comment": "Mechanical Locking Device 2 Retracted",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_2+CR-B5",
  "addr": "%I788.5",
  "type": "Bool",
  "comment": "Carrier Chain 3 OK",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_2+CR-B6",
  "addr": "%I788.6",
  "type": "Bool",
  "comment": "Mechanical Locking Device 3 Retracted",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_2+CR-B7",
  "addr": "%I788.7",
  "type": "Bool",
  "comment": "Carrier Chain 4 OK",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_2+CR-B8",
  "addr": "%I789.0",
  "type": "Bool",
  "comment": "Mechanical Locking Device 4 Retracted",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_2+CR-W1",
  "addr": "%I789.1",
  "type": "Bool",
  "comment": "Detection Carrier Infeed/Outfeed Position",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL1+HC1-PX.001",
  "addr": "%I789.6",
  "type": "Bool",
  "comment": "Level 1 Handover 1 Paddle Stop Prox Down A",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL1+HC1-PX.002",
  "addr": "%I789.7",
  "type": "Bool",
  "comment": "Level 1 Handover 1 Paddle Stop Prox Down B",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_1+TC-S1",
  "addr": "%I790.0",
  "type": "Bool",
  "comment": "Top Limit Switch 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_1+TC-S2",
  "addr": "%I790.1",
  "type": "Bool",
  "comment": "Top Limit Switch 2",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_2+TC-S1",
  "addr": "%I790.4",
  "type": "Bool",
  "comment": "Top Limit Switch 1",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_2+TC-S2",
  "addr": "%I790.5",
  "type": "Bool",
  "comment": "Top Limit Switch 2",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=ELV2+CR-PX.003",
  "addr": "%I791.0",
  "type": "Bool",
  "comment": "End Stop Down 2A",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=ELV2+CR-PX.006",
  "addr": "%I791.1",
  "type": "Bool",
  "comment": "End Stop Shaft Home 2B",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=ELV2+CR-PX.001",
  "addr": "%I791.2",
  "type": "Bool",
  "comment": "Carriage Retracted 2",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=ELV2+CR-PX.002",
  "addr": "%I791.3",
  "type": "Bool",
  "comment": "Carriage Extendedd 2",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=ELV2+CR-PX.004",
  "addr": "%I791.4",
  "type": "Bool",
  "comment": "End Stop Down 2B",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=ELV2+CR-PX.005",
  "addr": "%I791.5",
  "type": "Bool",
  "comment": "End Stop Shaft Home 2A",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=ELV2+CR-SEN.003",
  "addr": "%I791.6",
  "type": "Bool",
  "comment": "",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=ELV2+CR-SEN.002",
  "addr": "%I791.7",
  "type": "Bool",
  "comment": "",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=ELV1+CR-PX.001",
  "addr": "%I792.0",
  "type": "Bool",
  "comment": "",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=ELV1+CR-PX.006",
  "addr": "%I792.1",
  "type": "Bool",
  "comment": "",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=ELV1+CR-PX.003",
  "addr": "%I792.2",
  "type": "Bool",
  "comment": "",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=ELV1+CR-PX.004",
  "addr": "%I792.3",
  "type": "Bool",
  "comment": "",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=ELV1+CR-PX.005",
  "addr": "%I792.4",
  "type": "Bool",
  "comment": "",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=ELV1+CR-PX.002",
  "addr": "%I792.5",
  "type": "Bool",
  "comment": "",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=ELV1+CR-SEN.001",
  "addr": "%I792.7",
  "type": "Bool",
  "comment": "",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=LVL1+HC2-SEN.003",
  "addr": "%I794.1",
  "type": "Bool",
  "comment": "",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=ELV2+CR-SEN.001",
  "addr": "%I794.5",
  "type": "Bool",
  "comment": "",
  "table": "IO_DIGITAL_IN",
  "kind": "di"
 },
 {
  "name": "=PR10_1+CR-Y1",
  "addr": "%Q254.0",
  "type": "Bool",
  "comment": "Mechanical Locking Device Clamp Magnet 1",
  "table": "IO_DIGITAL_OUT",
  "kind": "do"
 },
 {
  "name": "=PR10_1+CR-Y2",
  "addr": "%Q254.1",
  "type": "Bool",
  "comment": "Mechanical Locking Device Clamp Magnet 2",
  "table": "IO_DIGITAL_OUT",
  "kind": "do"
 },
 {
  "name": "=PR10_1+CR-Y3",
  "addr": "%Q254.2",
  "type": "Bool",
  "comment": "Mechanical Locking Device Clamp Magnet 3",
  "table": "IO_DIGITAL_OUT",
  "kind": "do"
 },
 {
  "name": "=PR10_1+CR-Y4",
  "addr": "%Q254.3",
  "type": "Bool",
  "comment": "Mechanical Locking Device Clamp Magnet 4",
  "table": "IO_DIGITAL_OUT",
  "kind": "do"
 },
 {
  "name": "=PR10_2+CR-Y1",
  "addr": "%Q254.4",
  "type": "Bool",
  "comment": "Mechanical Locking Device Clamp Magnet 1",
  "table": "IO_DIGITAL_OUT",
  "kind": "do"
 },
 {
  "name": "=PR10_2+CR-Y2",
  "addr": "%Q254.5",
  "type": "Bool",
  "comment": "Mechanical Locking Device Clamp Magnet 2",
  "table": "IO_DIGITAL_OUT",
  "kind": "do"
 },
 {
  "name": "=PR10_2+CR-Y3",
  "addr": "%Q254.6",
  "type": "Bool",
  "comment": "Mechanical Locking Device Clamp Magnet 3",
  "table": "IO_DIGITAL_OUT",
  "kind": "do"
 },
 {
  "name": "=PR10_2+CR-Y4",
  "addr": "%Q254.7",
  "type": "Bool",
  "comment": "Mechanical Locking Device Clamp Magnet 4",
  "table": "IO_DIGITAL_OUT",
  "kind": "do"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyInputCard_01_I_0",
  "addr": "%I242.0",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "di"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyInputCard_01_I_1",
  "addr": "%I242.1",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "di"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyInputCard_01_I_2",
  "addr": "%I242.2",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "di"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyInputCard_01_I_3",
  "addr": "%I242.3",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "di"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyInputCard_01_I_4",
  "addr": "%I242.4",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "di"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyInputCard_01_I_5",
  "addr": "%I242.5",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "di"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyInputCard_01_I_6",
  "addr": "%I242.6",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "di"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyInputCard_01_I_7",
  "addr": "%I242.7",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "di"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyInputCard_01_I_0(1)",
  "addr": "%I736.0",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "di"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyInputCard_01_I_1(1)",
  "addr": "%I736.1",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "di"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyInputCard_01_I_2(1)",
  "addr": "%I736.2",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "di"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyInputCard_01_I_3(1)",
  "addr": "%I736.3",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "di"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyInputCard_01_I_4(1)",
  "addr": "%I736.4",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "di"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyInputCard_01_I_5(1)",
  "addr": "%I736.5",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "di"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyInputCard_01_I_6(1)",
  "addr": "%I736.6",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "di"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyInputCard_01_I_7(1)",
  "addr": "%I736.7",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "di"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyOutputCard_01_I_0",
  "addr": "%Q764.0",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "do"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyOutputCard_01_I_1",
  "addr": "%Q764.1",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "do"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyOutputCard_01_I_2",
  "addr": "%Q764.2",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "do"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyOutputCard_01_I_3",
  "addr": "%Q764.3",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "do"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyOutputCard_01_I_4",
  "addr": "%Q764.4",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "do"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyOutputCard_01_I_5",
  "addr": "%Q764.5",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "do"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyOutputCard_01_I_6",
  "addr": "%Q764.6",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "do"
 },
 {
  "name": "IO_RIO_01_Rack0_SafetyOutputCard_01_I_7",
  "addr": "%Q764.7",
  "type": "Bool",
  "comment": "",
  "table": "IO_SAFETY_TAGS",
  "kind": "do"
 },
 {
  "name": "MOVU_Q_CIN001",
  "addr": "%QW770",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_Q_CIN002",
  "addr": "%QW772",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_Q_CIN003",
  "addr": "%QW774",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_Q_CIN004",
  "addr": "%QW776",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_Q_CIN005",
  "addr": "%QW778",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_Q_CIN006",
  "addr": "%QW780",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_Q_CIN007",
  "addr": "%QW782",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_Q_CIN008",
  "addr": "%QW784",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_Q_CIN009",
  "addr": "%QW786",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_Q_CIN010",
  "addr": "%QW788",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_Q_CIN011",
  "addr": "%QW790",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_Q_CIN012",
  "addr": "%QW792",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_Q_CIN013",
  "addr": "%QW794",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_Q_CIN014",
  "addr": "%QW796",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_Q_CIN015",
  "addr": "%QW798",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN001",
  "addr": "%IW800",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN016",
  "addr": "%QW800",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN002",
  "addr": "%IW802",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN017",
  "addr": "%QW802",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN003",
  "addr": "%IW804",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN018",
  "addr": "%QW804",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN004",
  "addr": "%IW806",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN019",
  "addr": "%QW806",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN005",
  "addr": "%IW808",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN020",
  "addr": "%QW808",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN006",
  "addr": "%IW810",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN021",
  "addr": "%QW810",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN007",
  "addr": "%IW812",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN022",
  "addr": "%QW812",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN008",
  "addr": "%IW814",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN023",
  "addr": "%QW814",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN009",
  "addr": "%IW816",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN024",
  "addr": "%QW816",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN010",
  "addr": "%IW818",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN025",
  "addr": "%QW818",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN011",
  "addr": "%IW820",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN026",
  "addr": "%QW820",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN012",
  "addr": "%IW822",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN027",
  "addr": "%QW822",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN013",
  "addr": "%IW824",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN028",
  "addr": "%QW824",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN014",
  "addr": "%IW826",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN029",
  "addr": "%QW826",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN015",
  "addr": "%IW828",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN030",
  "addr": "%QW828",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN016",
  "addr": "%IW830",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN031",
  "addr": "%QW830",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN017",
  "addr": "%IW832",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN032",
  "addr": "%QW832",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN018",
  "addr": "%IW834",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN033",
  "addr": "%QW834",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN019",
  "addr": "%IW836",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN034",
  "addr": "%QW836",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN020",
  "addr": "%IW838",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN035",
  "addr": "%QW838",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN021",
  "addr": "%IW840",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN036",
  "addr": "%QW840",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN022",
  "addr": "%IW842",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN037",
  "addr": "%QW842",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN023",
  "addr": "%IW844",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN038",
  "addr": "%QW844",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN024",
  "addr": "%IW846",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN039",
  "addr": "%QW846",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN025",
  "addr": "%IW848",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN040",
  "addr": "%QW848",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN026",
  "addr": "%IW850",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN041",
  "addr": "%QW850",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN027",
  "addr": "%IW852",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN042",
  "addr": "%QW852",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN028",
  "addr": "%IW854",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN043",
  "addr": "%QW854",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN029",
  "addr": "%IW856",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN044",
  "addr": "%QW856",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN030",
  "addr": "%IW858",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN045",
  "addr": "%QW858",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN031",
  "addr": "%IW860",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN046",
  "addr": "%QW860",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN032",
  "addr": "%IW862",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN047",
  "addr": "%QW862",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN033",
  "addr": "%IW864",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN048",
  "addr": "%QW864",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN034",
  "addr": "%IW866",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN049",
  "addr": "%QW866",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN035",
  "addr": "%IW868",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN050",
  "addr": "%QW868",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN036",
  "addr": "%IW870",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN051",
  "addr": "%QW870",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN037",
  "addr": "%IW872",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN052",
  "addr": "%QW872",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN038",
  "addr": "%IW874",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN053",
  "addr": "%QW874",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN039",
  "addr": "%IW876",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN054",
  "addr": "%QW876",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN040",
  "addr": "%IW878",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN055",
  "addr": "%QW878",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN041",
  "addr": "%IW880",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN056",
  "addr": "%QW880",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN042",
  "addr": "%IW882",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN057",
  "addr": "%QW882",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN043",
  "addr": "%IW884",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN058",
  "addr": "%QW884",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN044",
  "addr": "%IW886",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN059",
  "addr": "%QW886",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN045",
  "addr": "%IW888",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN060",
  "addr": "%QW888",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN046",
  "addr": "%IW890",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN061",
  "addr": "%QW890",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN047",
  "addr": "%IW892",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN062",
  "addr": "%QW892",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN048",
  "addr": "%IW894",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN063",
  "addr": "%QW894",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN049",
  "addr": "%IW896",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN064",
  "addr": "%QW896",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN050",
  "addr": "%IW898",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN065",
  "addr": "%QW898",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN051",
  "addr": "%IW900",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN066",
  "addr": "%QW900",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN052",
  "addr": "%IW902",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN067",
  "addr": "%QW902",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN053",
  "addr": "%IW904",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN068",
  "addr": "%QW904",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN054",
  "addr": "%IW906",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN069",
  "addr": "%QW906",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN055",
  "addr": "%IW908",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN070",
  "addr": "%QW908",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN056",
  "addr": "%IW910",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN071",
  "addr": "%QW910",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN057",
  "addr": "%IW912",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN072",
  "addr": "%QW912",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN058",
  "addr": "%IW914",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN073",
  "addr": "%QW914",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN059",
  "addr": "%IW916",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN074",
  "addr": "%QW916",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN060",
  "addr": "%IW918",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN075",
  "addr": "%QW918",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN061",
  "addr": "%IW920",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN076",
  "addr": "%QW920",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN062",
  "addr": "%IW922",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN077",
  "addr": "%QW922",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN063",
  "addr": "%IW924",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN078",
  "addr": "%QW924",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN064",
  "addr": "%IW926",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN079",
  "addr": "%QW926",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN065",
  "addr": "%IW928",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN080",
  "addr": "%QW928",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN066",
  "addr": "%IW930",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN081",
  "addr": "%QW930",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN067",
  "addr": "%IW932",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN082",
  "addr": "%QW932",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN068",
  "addr": "%IW934",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN083",
  "addr": "%QW934",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN069",
  "addr": "%IW936",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN084",
  "addr": "%QW936",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN070",
  "addr": "%IW938",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN085",
  "addr": "%QW938",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN071",
  "addr": "%IW940",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN086",
  "addr": "%QW940",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN072",
  "addr": "%IW942",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN087",
  "addr": "%QW942",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN073",
  "addr": "%IW944",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN088",
  "addr": "%QW944",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN074",
  "addr": "%IW946",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN089",
  "addr": "%QW946",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN075",
  "addr": "%IW948",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN090",
  "addr": "%QW948",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN076",
  "addr": "%IW950",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN091",
  "addr": "%QW950",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN077",
  "addr": "%IW952",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN092",
  "addr": "%QW952",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN078",
  "addr": "%IW954",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN093",
  "addr": "%QW954",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN079",
  "addr": "%IW956",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN094",
  "addr": "%QW956",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN080",
  "addr": "%IW958",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN095",
  "addr": "%QW958",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN081",
  "addr": "%IW960",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN096",
  "addr": "%QW960",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN082",
  "addr": "%IW962",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN097",
  "addr": "%QW962",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN083",
  "addr": "%IW964",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN098",
  "addr": "%QW964",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN084",
  "addr": "%IW966",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN099",
  "addr": "%QW966",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN085",
  "addr": "%IW968",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_Q_CIN100",
  "addr": "%QW968",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_CIN086",
  "addr": "%IW970",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_CIN087",
  "addr": "%IW972",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_CIN088",
  "addr": "%IW974",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_CIN089",
  "addr": "%IW976",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_CIN090",
  "addr": "%IW978",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_CIN091",
  "addr": "%IW980",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_CIN092",
  "addr": "%IW982",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_CIN093",
  "addr": "%IW984",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_CIN094",
  "addr": "%IW986",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_CIN095",
  "addr": "%IW988",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_CIN096",
  "addr": "%IW990",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_CIN097",
  "addr": "%IW992",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_CIN098",
  "addr": "%IW994",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_CIN099",
  "addr": "%IW996",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_CIN100",
  "addr": "%IW998",
  "type": "Word",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_ZoneInterface_Q_General",
  "addr": "%QB1198",
  "type": "Byte",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_ZoneInterface_Q_Zone1",
  "addr": "%QB1199",
  "type": "Byte",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_ZoneInterface_Q_Zone2",
  "addr": "%QB1200",
  "type": "Byte",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_ZoneInterface_Q_Zone3",
  "addr": "%QB1201",
  "type": "Byte",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_ZoneInterface_Q_Zone4",
  "addr": "%QB1202",
  "type": "Byte",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_ZoneInterface_Q_Zone5",
  "addr": "%QB1203",
  "type": "Byte",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_ZoneInterface_Q_Zone6",
  "addr": "%QB1204",
  "type": "Byte",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_ZoneInterface_Q_Zone7",
  "addr": "%QB1205",
  "type": "Byte",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_ZoneInterface_Q_Zone8",
  "addr": "%QB1206",
  "type": "Byte",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_ZoneInterface_Q_Zone9",
  "addr": "%QB1207",
  "type": "Byte",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ao"
 },
 {
  "name": "MOVU_ZoneInterface_General",
  "addr": "%IB1224",
  "type": "Byte",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_ZoneInterface_Zone1",
  "addr": "%IB1225",
  "type": "Byte",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_ZoneInterface_Zone2",
  "addr": "%IB1226",
  "type": "Byte",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_ZoneInterface_Zone3",
  "addr": "%IB1227",
  "type": "Byte",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_ZoneInterface_Zone4",
  "addr": "%IB1228",
  "type": "Byte",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_ZoneInterface_Zone5",
  "addr": "%IB1229",
  "type": "Byte",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_ZoneInterface_Zone6",
  "addr": "%IB1230",
  "type": "Byte",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_ZoneInterface_Zone7",
  "addr": "%IB1231",
  "type": "Byte",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_ZoneInterface_Zone8",
  "addr": "%IB1232",
  "type": "Byte",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "MOVU_ZoneInterface_Zone9",
  "addr": "%IB1233",
  "type": "Byte",
  "comment": "",
  "table": "MOVU_Handshake",
  "kind": "ai"
 },
 {
  "name": "=PR10_2+LP-BG1",
  "addr": "%IW242",
  "type": "Word",
  "comment": "",
  "table": "Tag table_1",
  "kind": "ai"
 },
 {
  "name": "=PR10_1+LP-BG1",
  "addr": "%IW252",
  "type": "Word",
  "comment": "",
  "table": "Tag table_1",
  "kind": "ai"
 }
];
