import { useState, useRef, useEffect, useCallback } from "react";
import {
  Send,
  Loader2,
  Trash2,
  ChevronDown,
  ChevronRight,
  Wrench,
  Bot,
  User,
  Play,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  Square,
  Brain,
  SkipForward,
  Save,
  Check,
} from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useCompileFix } from "@/hooks/use-compile-fix";
import { useReimportCompile } from "@/hooks/use-reimport-compile";
import { useActivePatterns, useCreateApprovedPattern } from "@/hooks/use-patterns";
import { usePatternLibrarianAnalysis } from "@/hooks/use-pattern-librarian-analysis";
import { computeDiff, hasFunctionalChanges, extractFocusedSnippets } from "@/lib/diff-engine";
import { classifyCorrections } from "@/lib/correction-classifier";
import { TiaManualFixPanel } from "@/components/tia-console/tia-manual-fix-panel";
import type { CompileErrorInfo } from "@/lib/compile-fix-prompt";
import type { FixedSource } from "@/lib/compile-fix-parser";
import type { DesignProfile, AgentKnowledgeDoc, Project, FbTemplate, CorrectionType } from "@/types";
import type { PipelineStepResult } from "@/lib/pipeline";
import type {
  CompileFixMessage,
  CompileFixStuckInfo,
  CompileFixRoundSnapshot,
  CompileFixVerificationCorrection,
  CompileFixVerificationState,
  CompileFixSessionData,
} from "@/stores/tia-console-store";

const CORRECTION_TYPE_OPTIONS: CorrectionType[] = [
  "NAMING", "IO_MAPPING", "STATE_LOGIC", "ALARM", "SAFETY", "TIMING",
];

const DEFAULT_MAX_ROUNDS = 5;

interface CompileFixChatProps {
  compileErrors: CompileErrorInfo[];
  compileWarnings: CompileErrorInfo[];
  sources: Record<string, string>;
  isConnected: boolean;
  onCompileResultUpdate?: (result: {
    success: boolean;
    errors: CompileErrorInfo[];
    warnings: CompileErrorInfo[];
    sources: Record<string, string>;
  }) => void;
  /** Called when the fix session is fully done (user dismissed remember prompt or cleared chat) */
  onFixSessionEnd?: () => void;
  /** Optional design profile for customer-specific code rules */
  designProfile?: DesignProfile;
  /** Agent knowledge docs for the Code Architect (injected into compile-fix prompts) */
  agentKnowledgeDocs?: AgentKnowledgeDoc[];
  /** Pattern Librarian knowledge docs (injected into correction analysis prompts) */
  patternLibrarianKnowledgeDocs?: AgentKnowledgeDoc[];
  /** Custom prompt sections (DB overrides) */
  promptSections?: Record<string, string>;
  /** Project context for IO list, CPU type, safety level, etc. */
  project?: Project;
  /** FB templates for company-standard block structures */
  fbTemplates?: FbTemplate[];
  /** Previous pipeline steps (plan, generate, review) — passed as context so compile fix knows WHY the code was written */
  generationPipelineSteps?: PipelineStepResult[];
  /** Callback to emit pipeline steps for the Pipeline Console */
  onStepUpdate?: (updater: (prev: PipelineStepResult[]) => PipelineStepResult[]) => void;
  /** Saved compile-fix session from Zustand store (survives navigation) */
  savedSession?: CompileFixSessionData | null;
  /** Callback to persist session state to the store */
  onSessionChange?: (session: CompileFixSessionData | null) => void;
}

/** Build a context summary from the generation pipeline steps so the compile fix agent knows the full history. */
function buildPipelineContext(steps: PipelineStepResult[]): string {
  if (steps.length === 0) return "";

  const parts: string[] = ["## Generation Pipeline Context\n\nThe code you are fixing was generated by the following pipeline:\n"];

  for (const step of steps) {
    // Skip compile_fix steps (those are our own previous rounds)
    if (step.role === "compile_fix") continue;
    if (step.status !== "completed") continue;

    const roleLabel =
      step.role === "plan" ? "PM Plan" :
      step.role === "generate" ? "Code Generation" :
      step.role === "review" ? "Review Findings" :
      step.role === "rewrite" ? "Code Rewrite" :
      step.role === "patterns" ? "Pattern Analysis" :
      step.role === "summary" ? "PM Summary" :
      step.role;

    parts.push(`### ${step.agentName} — ${roleLabel}`);

    // Include the user message (contains the original request for plan/generate steps)
    if (step.role === "plan" && step.userMessage) {
      parts.push(`**Original Request:**\n${step.userMessage.slice(0, 2000)}`);
    }

    // Include a trimmed response (plan, review findings, summary are most useful)
    if (step.rawResponse && (step.role === "plan" || step.role === "review" || step.role === "summary")) {
      parts.push(`**Response:**\n${step.rawResponse.slice(0, 3000)}`);
    }

    // For generate/rewrite, just note what was produced (code is already in the sources)
    if (step.role === "generate" || step.role === "rewrite") {
      const artifacts = step.artifactsModified.length > 0
        ? step.artifactsModified.join(", ")
        : "code artifacts";
      parts.push(`**Produced:** ${artifacts}`);
    }

    parts.push("");
  }

  return parts.join("\n");
}

/** Fingerprint errors for stuck detection */
function errorFingerprint(errors: CompileErrorInfo[]): string {
  return errors
    .map((e) => `${e.artifact_name}:${e.line ?? ""}:${e.error_text}`)
    .sort()
    .join("|");
}

export function CompileFixChat({
  compileErrors,
  compileWarnings,
  sources,
  isConnected,
  onCompileResultUpdate,
  onFixSessionEnd,
  designProfile,
  agentKnowledgeDocs,
  patternLibrarianKnowledgeDocs,
  promptSections,
  project,
  fbTemplates,
  generationPipelineSteps,
  onStepUpdate,
  savedSession,
  onSessionChange,
}: CompileFixChatProps) {
  // Hydrate from saved session if available (survives navigation)
  const ss = savedSession;
  const [messages, setMessages] = useState<CompileFixMessage[]>(() => ss?.messages ?? []);
  const [input, setInput] = useState("");
  const [maxRounds, setMaxRounds] = useState(DEFAULT_MAX_ROUNDS);
  const maxRoundsRef = useRef(DEFAULT_MAX_ROUNDS);
  const [currentSources, setCurrentSources] = useState<Record<string, string>>(() => ss?.currentSources ?? sources);
  const [currentErrors, setCurrentErrors] = useState<CompileErrorInfo[]>(() => ss?.currentErrors ?? compileErrors);
  const [currentWarnings, setCurrentWarnings] = useState<CompileErrorInfo[]>(() => ss?.currentWarnings ?? compileWarnings);
  const [autoRunning, setAutoRunning] = useState(false);
  const autoRunningRef = useRef(false);
  const [round, setRound] = useState(() => ss?.round ?? 0);
  const [resolved, setResolved] = useState(() => ss?.resolved ?? false);
  const [stuck, setStuck] = useState<CompileFixStuckInfo | null>(() => ss?.stuck ?? null);
  const scrollRef = useRef<HTMLDivElement>(null);
  const prevFingerprintRef = useRef<string>("");
  const messagesRef = useRef<CompileFixMessage[]>(ss?.messages ?? []);

  // Per-round snapshot tracking for verification
  const [roundSnapshots, setRoundSnapshots] = useState<CompileFixRoundSnapshot[]>(() => ss?.roundSnapshots ?? []);
  const roundSnapshotsRef = useRef<CompileFixRoundSnapshot[]>(ss?.roundSnapshots ?? []);

  // Verification state machine
  const [verificationState, setVerificationState] = useState<CompileFixVerificationState>(() => ss?.verificationState ?? "idle");
  const [analyzingRound, setAnalyzingRound] = useState(0);
  const [verificationCorrections, setVerificationCorrections] = useState<CompileFixVerificationCorrection[]>(() => ss?.verificationCorrections ?? []);
  const verifyingRef = useRef(false);
  const [savedCount, setSavedCount] = useState(() => ss?.savedCount ?? 0);

  const compileFix = useCompileFix();
  const reimportCompile = useReimportCompile();
  const librarianAnalysis = usePatternLibrarianAnalysis();
  const { data: approvedPatterns } = useActivePatterns("SIEMENS_TIA");
  const createApprovedPattern = useCreateApprovedPattern();

  // Sync props into state on mount / when parent changes
  // Skip the initial sync if we hydrated from a saved session
  const hydratedRef = useRef(!!ss);
  useEffect(() => {
    if (hydratedRef.current) { hydratedRef.current = false; return; }
    setCurrentSources(sources);
  }, [sources]);

  useEffect(() => {
    if (hydratedRef.current) return;
    setCurrentErrors(compileErrors);
    setCurrentWarnings(compileWarnings);
  }, [compileErrors, compileWarnings]);

  // Keep refs in sync
  useEffect(() => {
    messagesRef.current = messages;
  }, [messages]);
  useEffect(() => {
    maxRoundsRef.current = maxRounds;
  }, [maxRounds]);
  useEffect(() => {
    roundSnapshotsRef.current = roundSnapshots;
  }, [roundSnapshots]);

  // Persist session state to Zustand store (survives navigation)
  useEffect(() => {
    // Only persist when there's meaningful session state
    if (messages.length === 0 && !resolved && !stuck) {
      return;
    }
    onSessionChange?.({
      messages,
      round,
      resolved,
      stuck,
      currentSources,
      currentErrors,
      currentWarnings,
      roundSnapshots,
      verificationState,
      verificationCorrections,
      savedCount,
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [messages, round, resolved, stuck, currentSources, currentErrors, currentWarnings, roundSnapshots, verificationState, verificationCorrections, savedCount]);

  // Trigger verification prompt when fix resolves successfully
  useEffect(() => {
    if (!resolved) return;
    if (verificationState !== "idle") return;
    setVerificationState("prompting");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [resolved]);

  // Auto-scroll on new messages or state changes
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages, resolved, stuck, verificationState]);

  // Helper: synchronously set autoRunning flag + ref
  const setAutoRunningSync = useCallback((value: boolean) => {
    autoRunningRef.current = value;
    setAutoRunning(value);
  }, []);

  // --- Core auto-loop: ask AI → apply fixes → recompile → repeat ---

  const askAI = useCallback(
    (
      errors: CompileErrorInfo[],
      warnings: CompileErrorInfo[],
      srcs: Record<string, string>,
      roundNum: number,
      userMsg?: string,
    ) => {
      const isFirst = roundNum === 1;
      const prefix = isFirst
        ? `Fix ${errors.length} compile error(s)`
        : `Round ${roundNum}: Fix remaining ${errors.length} error(s)`;
      const displayMessage = userMsg ? `${prefix}\n${userMsg}` : prefix;

      // On the first round, prepend pipeline context so the compile fix agent
      // knows the original request, PM plan, and review findings
      let enrichedUserMsg = userMsg;
      if (isFirst && generationPipelineSteps && generationPipelineSteps.length > 0) {
        const pipelineContext = buildPipelineContext(generationPipelineSteps);
        if (pipelineContext) {
          enrichedUserMsg = pipelineContext + (userMsg ? `\n\n${userMsg}` : "");
        }
      }

      // Build conversation history from prior messages so the AI doesn't repeat mistakes
      const conversationHistory = messagesRef.current
        .filter((m) => m.role === "user" || m.role === "assistant")
        .map((m) => ({ role: m.role as "user" | "assistant", content: m.content }));

      setMessages((prev) => [...prev, { role: "user", content: displayMessage }]);

      // Emit a "running" pipeline step
      const stepStartTime = Date.now();
      onStepUpdate?.((prev) => [
        ...prev,
        {
          agentId: "compile-fix",
          agentName: "Code Architect",
          role: "compile_fix" as PipelineStepResult["role"],
          status: "running",
          systemPrompt: "",
          userMessage: displayMessage,
          rawResponse: "",
          tokenUsage: null,
          durationMs: 0,
          artifactsModified: [],
          summary: `Round ${roundNum}: fixing ${errors.length} error(s)${userMsg ? ` — ${userMsg}` : ""}`,
        },
      ]);

      compileFix.mutate(
        {
          errors,
          warnings,
          sources: srcs,
          userMessage: enrichedUserMsg,
          approvedPatterns,
          conversationHistory,
          designProfile,
          agentKnowledgeDocs,
          promptSections,
          project,
          fbTemplates,
        },
        {
          onSuccess: (result) => {
            const durationMs = Date.now() - stepStartTime;

            // Update the running step to completed
            onStepUpdate?.((prev) => {
              const updated = [...prev];
              // Find last running compile_fix step
              for (let i = updated.length - 1; i >= 0; i--) {
                if (updated[i].role === "compile_fix" && updated[i].status === "running") {
                  updated[i] = {
                    ...updated[i],
                    status: "completed",
                    systemPrompt: result.systemPrompt,
                    userMessage: result.userMessage,
                    rawResponse: result.rawResponse,
                    tokenUsage: result.tokenUsage,
                    durationMs,
                    artifactsModified: result.fixes.map((f) => f.artifactName),
                    summary: `Round ${roundNum}: ${result.fixes.length} file(s) corrected${userMsg ? ` — ${userMsg}` : ""}`,
                  };
                  break;
                }
              }
              return updated;
            });

            // Check ref — user may have cancelled while waiting
            if (!autoRunningRef.current) return;

            const msg: CompileFixMessage = {
              role: "assistant",
              content: result.explanation || result.rawResponse,
              fixes: result.fixes.length > 0 ? result.fixes : undefined,
            };
            setMessages((prev) => [...prev, msg]);

            // If AI returned fixes and we're auto-running, apply them immediately
            if (result.fixes.length > 0 && autoRunningRef.current) {
              applyAndRecompile(result.fixes, srcs, errors, roundNum, result.explanation || result.rawResponse);
            }
          },
          onError: (error) => {
            const durationMs = Date.now() - stepStartTime;

            // Mark the running step as failed
            onStepUpdate?.((prev) => {
              const updated = [...prev];
              for (let i = updated.length - 1; i >= 0; i--) {
                if (updated[i].role === "compile_fix" && updated[i].status === "running") {
                  updated[i] = {
                    ...updated[i],
                    status: "failed",
                    durationMs,
                    error: error.message,
                    summary: `Round ${roundNum}: failed — ${error.message}`,
                  };
                  break;
                }
              }
              return updated;
            });

            setMessages((prev) => [
              ...prev,
              { role: "system", content: `Error: ${error.message}` },
            ]);
            setAutoRunningSync(false);
          },
        },
      );
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [compileFix, setAutoRunningSync, approvedPatterns, agentKnowledgeDocs, onStepUpdate, generationPipelineSteps],
  );

  const applyAndRecompile = useCallback(
    (
      fixes: FixedSource[],
      srcs: Record<string, string>,
      prevErrors: CompileErrorInfo[],
      roundNum: number,
      explanation?: string,
    ) => {
      // Merge fixes
      const updated = { ...srcs };
      for (const fix of fixes) {
        updated[fix.artifactName] = fix.content;
      }
      setCurrentSources(updated);

      // Mark latest assistant message as applied
      setMessages((prev) => {
        const last = [...prev];
        for (let i = last.length - 1; i >= 0; i--) {
          if (last[i].role === "assistant" && last[i].fixes && !last[i].appliedFixes) {
            last[i] = { ...last[i], appliedFixes: true };
            break;
          }
        }
        return last;
      });

      setMessages((prev) => [
        ...prev,
        { role: "system", content: `Recompiling ${fixes.length} corrected source(s)...` },
      ]);

      reimportCompile.mutate(
        { sources: updated },
        {
          onSuccess: (result) => {
            // Check ref — user may have cancelled while waiting
            if (!autoRunningRef.current) {
              // Still update sources/errors even when cancelled, so state is current
              setCurrentSources(result.sources);
              setCurrentErrors(result.errors ?? []);
              setCurrentWarnings(result.warnings ?? []);
              onCompileResultUpdate?.({
                success: result.success,
                errors: result.errors ?? [],
                warnings: result.warnings ?? [],
                sources: result.sources,
              });
              return;
            }

            const newSources = result.sources;
            const newErrors = result.errors ?? [];
            const newWarnings = result.warnings ?? [];

            setCurrentSources(newSources);
            setCurrentErrors(newErrors);
            setCurrentWarnings(newWarnings);

            // Capture per-round snapshot for verification
            const snapshot: CompileFixRoundSnapshot = {
              round: roundNum,
              sourcesBefore: srcs,
              sourcesAfter: newSources,
              errorsAddressed: prevErrors,
              fixes,
              explanation: explanation ?? "",
            };
            roundSnapshotsRef.current = [...roundSnapshotsRef.current, snapshot];
            setRoundSnapshots(roundSnapshotsRef.current);

            // Notify parent
            onCompileResultUpdate?.({
              success: result.success,
              errors: newErrors,
              warnings: newWarnings,
              sources: newSources,
            });

            if (result.success) {
              // Resolved!
              setMessages((prev) => [
                ...prev,
                {
                  role: "system",
                  content: `Compile successful! All errors resolved in ${roundNum} round(s). ${newWarnings.length} warning(s).`,
                },
              ]);
              setAutoRunningSync(false);
              setResolved(true);
              return;
            }

            // Still errors — check if stuck
            const newFingerprint = errorFingerprint(newErrors);
            const sameErrors = newFingerprint === prevFingerprintRef.current;
            const noImprovement = newErrors.length >= prevErrors.length;
            const maxReached = roundNum >= maxRoundsRef.current;

            if (sameErrors || maxReached) {
              const reason = sameErrors
                ? "Same errors after applying fixes — the AI could not resolve them."
                : `Reached maximum of ${maxRoundsRef.current} fix rounds.`;

              setMessages((prev) => [
                ...prev,
                {
                  role: "system",
                  content: `Compile failed: ${newErrors.length} error(s). ${reason}`,
                },
              ]);
              setAutoRunningSync(false);
              setStuck({
                errors: newErrors,
                sources: newSources,
                rounds: roundNum,
                reason,
              });
              return;
            }

            // Progress made — continue loop
            prevFingerprintRef.current = newFingerprint;
            const nextRound = roundNum + 1;
            setRound(nextRound);

            setMessages((prev) => [
              ...prev,
              {
                role: "system",
                content: `Compile failed: ${newErrors.length} error(s) remaining (was ${prevErrors.length}). Continuing...`,
              },
            ]);

            // If auto-running and there's no improvement, warn but still try if error text differs
            if (noImprovement && !sameErrors) {
              setMessages((prev) => [
                ...prev,
                {
                  role: "system",
                  content: `Warning: error count didn't decrease. Trying different approach...`,
                },
              ]);
            }

            // Next round
            askAI(newErrors, newWarnings, newSources, nextRound);
          },
          onError: (error) => {
            setMessages((prev) => [
              ...prev,
              { role: "system", content: `Reimport failed: ${error.message}` },
            ]);
            setAutoRunningSync(false);
          },
        },
      );
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [reimportCompile, onCompileResultUpdate, askAI, setAutoRunningSync],
  );

  function handleAutoFix(userMsg?: string) {
    prevFingerprintRef.current = errorFingerprint(currentErrors);
    setAutoRunningSync(true);
    setResolved(false);
    setStuck(null);
    setRound(1);
    setRoundSnapshots([]);
    roundSnapshotsRef.current = [];
    setVerificationState("idle");
    setVerificationCorrections([]);
    setSavedCount(0);
    askAI(currentErrors, currentWarnings, currentSources, 1, userMsg);
  }

  function handleCancel() {
    setAutoRunningSync(false);
    setMessages((prev) => [
      ...prev,
      { role: "system", content: "Auto-fix cancelled by user." },
    ]);
  }

  function handleManualApply(fixes: FixedSource[], messageIndex: number) {
    // Mark this message as applied
    setMessages((prev) =>
      prev.map((m, i) => (i === messageIndex ? { ...m, appliedFixes: true } : m)),
    );

    // Apply without auto-loop
    const updated = { ...currentSources };
    for (const fix of fixes) {
      updated[fix.artifactName] = fix.content;
    }
    setCurrentSources(updated);

    setMessages((prev) => [
      ...prev,
      { role: "system", content: `Recompiling ${fixes.length} corrected source(s)...` },
    ]);

    reimportCompile.mutate(
      { sources: updated },
      {
        onSuccess: (result) => {
          setCurrentSources(result.sources);
          setCurrentErrors(result.errors ?? []);
          setCurrentWarnings(result.warnings ?? []);

          onCompileResultUpdate?.({
            success: result.success,
            errors: result.errors ?? [],
            warnings: result.warnings ?? [],
            sources: result.sources,
          });

          if (result.success) {
            setMessages((prev) => [
              ...prev,
              { role: "system", content: `Compile successful! ${(result.warnings ?? []).length} warning(s).` },
            ]);
            setResolved(true);
          } else {
            setMessages((prev) => [
              ...prev,
              {
                role: "system",
                content: `Compile failed: ${(result.errors ?? []).length} error(s). Click "Continue Fixing" or type instructions below.`,
              },
            ]);
          }
        },
        onError: (error) => {
          setMessages((prev) => [
            ...prev,
            { role: "system", content: `Reimport failed: ${error.message}` },
          ]);
        },
      },
    );
  }

  function handleSend() {
    const msg = input.trim();
    if (!msg && messages.length === 0) {
      handleAutoFix();
      return;
    }
    if (!msg) return;
    setInput("");

    if (messages.length === 0) {
      handleAutoFix(msg);
    } else {
      // Manual follow-up — restart auto-loop with instructions
      prevFingerprintRef.current = errorFingerprint(currentErrors);
      setAutoRunningSync(true);
      setStuck(null);
      setRound((r) => r + 1);
      askAI(currentErrors, currentWarnings, currentSources, round + 1, msg);
    }
  }

  function handleContinueFixing() {
    setStuck(null);
    prevFingerprintRef.current = "";
    setAutoRunningSync(true);
    const nextRound = round + 1;
    setRound(nextRound);
    askAI(currentErrors, currentWarnings, currentSources, nextRound);
  }

  function handleClear() {
    setMessages([]);
    setCurrentSources(sources);
    setCurrentErrors(compileErrors);
    setCurrentWarnings(compileWarnings);
    setAutoRunningSync(false);
    setResolved(false);
    setStuck(null);
    setRound(0);
    setRoundSnapshots([]);
    roundSnapshotsRef.current = [];
    setVerificationState("idle");
    setVerificationCorrections([]);
    setAnalyzingRound(0);
    verifyingRef.current = false;
    setSavedCount(0);
    onSessionChange?.(null);
    onFixSessionEnd?.();
    prevFingerprintRef.current = "";
  }

  // --- Verification handlers ---

  /** Quick Save: original → final diff with regex classification (old auto-learn behavior) */
  function handleQuickSave() {
    setVerificationState("saving");

    const lastAssistant = [...messagesRef.current].reverse().find(
      (m) => m.role === "assistant" && m.content,
    );

    let saved = 0;
    const changedArtifacts: string[] = [];

    for (const name of Object.keys(currentSources)) {
      const original = sources[name];
      const current = currentSources[name];
      if (!original || !current || original === current) continue;
      if (!hasFunctionalChanges(original, current)) continue;
      changedArtifacts.push(name);
    }

    if (changedArtifacts.length === 0) {
      setVerificationState("done");
      setSavedCount(0);
      return;
    }

    // Save one pattern per changed artifact
    let pending = changedArtifacts.length;
    for (const name of changedArtifacts) {
      const original = sources[name]!;
      const current = currentSources[name]!;
      const diff = computeDiff(original, current);
      const focused = extractFocusedSnippets(diff);
      const classified = classifyCorrections(diff, { artifactName: name });
      const correctionType = classified.length > 0 ? classified[0].correctionType : "STATE_LOGIC";

      createApprovedPattern.mutate(
        {
          plc_brand: "SIEMENS_TIA",
          device_type: "General",
          context: `compile-fix: ${name}`,
          original_snippet: focused.originalSnippet,
          corrected_snippet: focused.correctedSnippet,
          correction_type: correctionType,
          explanation_tag: lastAssistant?.content.slice(0, 2000) ?? `Compile-fix correction in ${name}`,
        },
        {
          onSuccess: () => {
            saved++;
            pending--;
            if (pending <= 0) {
              setSavedCount(saved);
              setVerificationState("done");
            }
          },
          onError: () => {
            pending--;
            if (pending <= 0) {
              setSavedCount(saved);
              setVerificationState("done");
            }
          },
        },
      );
    }
  }

  /** Skip: no patterns saved */
  function handleSkipPatterns() {
    setVerificationState("done");
    setSavedCount(0);
  }

  /** Verify: run Pattern Librarian on each round sequentially */
  async function handleVerifyRounds() {
    setVerificationState("analyzing");
    verifyingRef.current = true;

    const allCorrections: CompileFixVerificationCorrection[] = [];
    const snapshots = roundSnapshotsRef.current;

    for (let i = 0; i < snapshots.length; i++) {
      if (!verifyingRef.current) break;
      setAnalyzingRound(i + 1);

      const snap = snapshots[i];

      // Emit a running pipeline step
      const stepStartTime = Date.now();
      onStepUpdate?.((prev) => [
        ...prev,
        {
          agentId: "pattern-librarian-verify",
          agentName: "Pattern Librarian",
          role: "patterns" as PipelineStepResult["role"],
          status: "running",
          systemPrompt: "",
          userMessage: `Verifying round ${snap.round} corrections`,
          rawResponse: "",
          tokenUsage: null,
          durationMs: 0,
          artifactsModified: snap.fixes.map((f) => f.artifactName),
          summary: `Verifying round ${snap.round} of ${snapshots.length}`,
        },
      ]);

      try {
        const result = await librarianAnalysis.mutateAsync({
          originalSources: snap.sourcesBefore,
          correctedSources: snap.sourcesAfter,
          knowledgeDocs: patternLibrarianKnowledgeDocs,
          approvedPatterns,
          errorsAddressed: snap.errorsAddressed,
          roundNumber: snap.round,
          totalRounds: snapshots.length,
        });

        const durationMs = Date.now() - stepStartTime;

        // Update the pipeline step to completed
        onStepUpdate?.((prev) => {
          const updated = [...prev];
          for (let j = updated.length - 1; j >= 0; j--) {
            if (updated[j].role === "patterns" && updated[j].status === "running") {
              updated[j] = {
                ...updated[j],
                status: "completed",
                durationMs,
                summary: `Round ${snap.round}: ${result.corrections.length} correction(s) found${result.aiAnalyzed ? "" : " (regex)"}`,
              };
              break;
            }
          }
          return updated;
        });

        for (const c of result.corrections) {
          allCorrections.push({
            ...c,
            roundNumber: snap.round,
            checked: c.confidence >= 0.7 && !c.assessmentNote,
          });
        }
      } catch (err) {
        const durationMs = Date.now() - stepStartTime;
        console.warn(`Round ${i + 1} analysis failed:`, err);

        onStepUpdate?.((prev) => {
          const updated = [...prev];
          for (let j = updated.length - 1; j >= 0; j--) {
            if (updated[j].role === "patterns" && updated[j].status === "running") {
              updated[j] = {
                ...updated[j],
                status: "failed",
                durationMs,
                error: String(err),
                summary: `Round ${snap.round}: analysis failed`,
              };
              break;
            }
          }
          return updated;
        });
      }
    }

    if (!verifyingRef.current) {
      setVerificationState("prompting");
      return;
    }

    setVerificationCorrections(allCorrections);
    setVerificationState(allCorrections.length > 0 ? "reviewing" : "done");
  }

  /** Cancel verification analysis */
  function handleCancelVerification() {
    verifyingRef.current = false;
    setVerificationState("prompting");
  }

  /** Toggle a correction's checked state */
  function toggleCorrection(index: number) {
    setVerificationCorrections((prev) =>
      prev.map((c, i) => (i === index ? { ...c, checked: !c.checked } : c)),
    );
  }

  /** Update a correction's type */
  function updateCorrectionType(index: number, type: CorrectionType) {
    setVerificationCorrections((prev) =>
      prev.map((c, i) => (i === index ? { ...c, correctionType: type } : c)),
    );
  }

  /** Save checked verification corrections as approved patterns */
  function handleSaveVerifiedPatterns() {
    const toSave = verificationCorrections.filter((c) => c.checked);
    if (toSave.length === 0) {
      setSavedCount(0);
      setVerificationState("done");
      return;
    }

    setVerificationState("saving");
    let saved = 0;
    let pending = toSave.length;

    for (const c of toSave) {
      createApprovedPattern.mutate(
        {
          plc_brand: "SIEMENS_TIA",
          device_type: "General",
          context: `compile-fix round ${c.roundNumber}: ${c.blockName}`,
          original_snippet: c.originalSnippet,
          corrected_snippet: c.correctedSnippet,
          correction_type: c.correctionType,
          explanation_tag: c.explanation.slice(0, 2000),
        },
        {
          onSuccess: () => {
            saved++;
            pending--;
            if (pending <= 0) {
              setSavedCount(saved);
              setVerificationState("done");
            }
          },
          onError: () => {
            pending--;
            if (pending <= 0) {
              setSavedCount(saved);
              setVerificationState("done");
            }
          },
        },
      );
    }
  }

  function handleKeyDown(e: React.KeyboardEvent) {
    if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) {
      e.preventDefault();
      handleSend();
    }
  }

  const isLoading = compileFix.isPending || reimportCompile.isPending;

  return (
    <Card className="flex max-h-[600px] flex-col overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between border-b px-3 py-2">
        <div className="flex items-center gap-2">
          <Wrench className="h-3.5 w-3.5 text-amber-400" />
          <span className="font-mono text-sm font-medium">Compile Fix</span>
          {resolved ? (
            <Badge variant="outline" className="font-mono text-xs border-green-500/30 bg-green-500/10 text-green-400">
              Resolved
            </Badge>
          ) : (
            <Badge variant="outline" className="font-mono text-xs">
              {currentErrors.length} error{currentErrors.length !== 1 ? "s" : ""}
            </Badge>
          )}
          {autoRunning && (
            <Badge variant="outline" className="font-mono text-xs border-blue-500/30 bg-blue-500/10 text-blue-400">
              Round {round}/{maxRounds}
            </Badge>
          )}
        </div>
        <div className="flex items-center gap-1">
          {messages.length === 0 && (
            <>
              <Select value={String(maxRounds)} onValueChange={(v) => setMaxRounds(Number(v))}>
                <SelectTrigger className="h-5 w-14 font-mono text-xs" aria-label="Max auto-fix rounds">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {[1, 2, 3, 5, 7, 10].map((n) => (
                    <SelectItem key={n} value={String(n)} className="font-mono text-xs">{n}x</SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <Button
                variant="outline"
                size="sm"
                className="h-5 gap-1 px-2 font-mono text-xs"
                onClick={() => handleAutoFix()}
                disabled={isLoading || !isConnected}
              >
                <Bot className="h-2.5 w-2.5" />
                Auto-Fix
              </Button>
            </>
          )}
          {autoRunning && (
            <Button
              variant="outline"
              size="sm"
              className="h-5 gap-1 px-2 font-mono text-xs border-red-500/30 text-red-400 hover:bg-red-500/10"
              onClick={handleCancel}
            >
              <Square className="h-2 w-2" />
              Cancel
            </Button>
          )}
          <Button
            variant="ghost"
            size="sm"
            className="h-5 px-1.5"
            onClick={handleClear}
            disabled={messages.length === 0 || isLoading}
            aria-label="Clear chat"
          >
            <Trash2 className="h-2.5 w-2.5" aria-hidden="true" />
          </Button>
        </div>
      </div>

      {/* Messages */}
      <div ref={scrollRef} className="min-h-0 min-w-0 flex-1 overflow-x-hidden overflow-y-auto">
        <div className="space-y-2 p-3">
          {messages.length === 0 && (
            <div className="py-4 text-center font-mono text-sm text-muted-foreground">
              Click "Auto-Fix" to automatically fix compile errors with AI.
              <br />
              It will loop until all errors are resolved or it gets stuck.
            </div>
          )}

          {messages.map((msg, i) => (
            <MessageBubble
              key={i}
              message={msg}
              index={i}
              isLoading={isLoading}
              isConnected={isConnected}
              autoRunning={autoRunning}
              onApplyFixes={handleManualApply}
            />
          ))}

          {isLoading && (
            <div className="flex items-center gap-2 py-2 font-mono text-xs text-muted-foreground">
              <Loader2 className="h-3 w-3 animate-spin" />
              {compileFix.isPending ? "AI analyzing errors..." : "Reimporting & recompiling..."}
            </div>
          )}

          {/* Stuck panel */}
          {stuck && <StuckPanel stuck={stuck} />}

          {/* Post-recompile actions (when not auto-running and not resolved) */}
          {!autoRunning && !resolved && !stuck && messages.length > 0 && !isLoading && currentErrors.length > 0 && (
            <div className="flex gap-1.5 pt-2">
              <Button
                size="sm"
                variant="outline"
                className="h-6 flex-1 gap-1 font-mono text-xs"
                onClick={handleContinueFixing}
                disabled={isLoading || !isConnected}
              >
                <Play className="h-2.5 w-2.5" />
                Continue Fixing ({currentErrors.length} errors)
              </Button>
            </div>
          )}

          {/* Verification state machine */}
          {resolved && !autoRunning && !isLoading && (
            <VerificationPanel
              state={verificationState}
              roundCount={roundSnapshots.length}
              analyzingRound={analyzingRound}
              corrections={verificationCorrections}
              savedCount={savedCount}
              onVerify={handleVerifyRounds}
              onQuickSave={handleQuickSave}
              onSkip={handleSkipPatterns}
              onCancelAnalysis={handleCancelVerification}
              onToggleCorrection={toggleCorrection}
              onUpdateCorrectionType={updateCorrectionType}
              onSavePatterns={handleSaveVerifiedPatterns}
              onDismiss={() => onFixSessionEnd?.()}
            />
          )}

          {/* Manual fix panel — when stuck or errors remain */}
          {!resolved && !autoRunning && !isLoading && (stuck || currentErrors.length > 0) && messages.length > 0 && (
            <TiaManualFixPanel
              originalSources={sources}
              currentSources={currentSources}
              isConnected={isConnected}
              patternLibrarianKnowledgeDocs={patternLibrarianKnowledgeDocs}
              approvedPatterns={approvedPatterns}
              onLearningsSaved={() => {
                setMessages((prev) => [
                  ...prev,
                  { role: "system", content: "Manual fix patterns saved for future generations." },
                ]);
              }}
            />
          )}
        </div>
      </div>

      {/* Input */}
      <div className="border-t p-2">
        <div className="flex gap-1.5">
          <Textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder={
              messages.length === 0
                ? "Optional: Add context before auto-fix..."
                : stuck
                  ? "Give the AI additional instructions to try again..."
                  : "Add instructions for the next fix round..."
            }
            className="min-h-[36px] resize-none font-mono text-sm"
            rows={1}
            disabled={isLoading || autoRunning}
          />
          <Button
            size="sm"
            className="h-9 shrink-0 px-2"
            onClick={handleSend}
            disabled={isLoading || autoRunning || (!input.trim() && messages.length > 0)}
          >
            <Send className="h-3 w-3" />
          </Button>
        </div>
        <div className="mt-1 font-mono text-xs text-muted-foreground">
          Ctrl+Enter to send
        </div>
      </div>
    </Card>
  );
}


// --- Verification panel: post-fix pattern verification state machine ---

function VerificationPanel({
  state,
  roundCount,
  analyzingRound,
  corrections,
  savedCount,
  onVerify,
  onQuickSave,
  onSkip,
  onCancelAnalysis,
  onToggleCorrection,
  onUpdateCorrectionType,
  onSavePatterns,
  onDismiss,
}: {
  state: CompileFixVerificationState;
  roundCount: number;
  analyzingRound: number;
  corrections: CompileFixVerificationCorrection[];
  savedCount: number;
  onVerify: () => void;
  onQuickSave: () => void;
  onSkip: () => void;
  onCancelAnalysis: () => void;
  onToggleCorrection: (index: number) => void;
  onUpdateCorrectionType: (index: number, type: CorrectionType) => void;
  onSavePatterns: () => void;
  onDismiss: () => void;
}) {
  const [expandedBlocks, setExpandedBlocks] = useState<Set<number>>(new Set());

  function toggleBlock(index: number) {
    setExpandedBlocks((prev) => {
      const next = new Set(prev);
      if (next.has(index)) next.delete(index);
      else next.add(index);
      return next;
    });
  }

  if (state === "idle") return null;

  // --- Prompting ---
  if (state === "prompting") {
    return (
      <div className="space-y-2 rounded-lg border border-green-500/20 bg-green-500/5 p-3">
        <div className="flex items-center gap-2">
          <CheckCircle2 className="h-3.5 w-3.5 text-green-400" />
          <span className="font-mono text-sm font-medium text-green-400">
            Fix complete ({roundCount} round{roundCount !== 1 ? "s" : ""})
          </span>
        </div>
        <p className="font-mono text-xs text-muted-foreground">
          Would you like the AI to verify your fixes before saving patterns?
        </p>
        <div className="flex gap-1.5">
          <Button
            size="sm"
            variant="outline"
            className="h-6 gap-1 px-2 font-mono text-xs border-blue-500/30 text-blue-400 hover:bg-blue-500/10"
            onClick={onVerify}
          >
            <Brain className="h-2.5 w-2.5" />
            Verify Fixes
          </Button>
          <Button
            size="sm"
            variant="outline"
            className="h-6 gap-1 px-2 font-mono text-xs"
            onClick={onQuickSave}
          >
            <Save className="h-2.5 w-2.5" />
            Quick Save
          </Button>
          <Button
            size="sm"
            variant="ghost"
            className="h-6 gap-1 px-2 font-mono text-xs"
            onClick={onSkip}
          >
            <SkipForward className="h-2.5 w-2.5" />
            Skip
          </Button>
        </div>
        <p className="font-mono text-[10px] text-muted-foreground/70">
          &quot;Verify Fixes&quot; runs the Pattern Librarian on each round&apos;s changes to assess confidence before saving.
        </p>
      </div>
    );
  }

  // --- Analyzing ---
  if (state === "analyzing") {
    return (
      <div className="space-y-2 rounded-lg border border-blue-500/20 bg-blue-500/5 p-3">
        <div className="flex items-center gap-2">
          <Brain className="h-3.5 w-3.5 animate-pulse text-blue-400" />
          <span className="font-mono text-sm font-medium text-blue-400">
            Analyzing round {analyzingRound} of {roundCount}...
          </span>
        </div>
        <Button
          size="sm"
          variant="ghost"
          className="h-6 px-2 font-mono text-xs text-muted-foreground"
          onClick={onCancelAnalysis}
        >
          Cancel
        </Button>
      </div>
    );
  }

  // --- Reviewing ---
  if (state === "reviewing") {
    const checkedCount = corrections.filter((c) => c.checked).length;
    const groupedByRound = new Map<number, Array<{ correction: CompileFixVerificationCorrection; idx: number }>>();
    corrections.forEach((c, i) => {
      const group = groupedByRound.get(c.roundNumber) ?? [];
      group.push({ correction: c, idx: i });
      groupedByRound.set(c.roundNumber, group);
    });

    return (
      <div className="space-y-2 rounded-lg border border-blue-500/20 bg-blue-500/5 p-3">
        <div className="flex items-center gap-2">
          <Brain className="h-3.5 w-3.5 text-blue-400" />
          <span className="font-mono text-sm font-medium text-blue-400">
            Verification Results
          </span>
          <Badge variant="outline" className="font-mono text-xs">
            {corrections.length} correction{corrections.length !== 1 ? "s" : ""}
          </Badge>
        </div>

        <div className="max-h-64 space-y-2 overflow-y-auto">
          {Array.from(groupedByRound.entries()).map(([roundNum, roundEntries]) => (
            <div key={roundNum} className="space-y-1">
              <div className="font-mono text-xs font-medium text-muted-foreground">
                Round {roundNum}
              </div>
              {roundEntries.map(({ correction: c, idx }) => {
                const isLowConfidence = c.confidence < 0.6;
                return (
                  <div
                    key={idx}
                    className={`rounded border p-2 ${
                      c.assessmentNote
                        ? "border-amber-500/30 bg-amber-500/5"
                        : isLowConfidence
                          ? "border-red-500/20 bg-red-500/5"
                          : "border-border/50 bg-muted/30"
                    }`}
                  >
                    <div className="flex items-start gap-2">
                      <Checkbox
                        checked={c.checked}
                        onCheckedChange={() => onToggleCorrection(idx)}
                        className="mt-0.5"
                      />
                      <div className="min-w-0 flex-1 space-y-1">
                        <div className="flex items-center gap-1.5">
                          <span className="font-mono text-xs font-medium">{c.blockName}</span>
                          <Select
                            value={c.correctionType}
                            onValueChange={(v) => onUpdateCorrectionType(idx, v as CorrectionType)}
                          >
                            <SelectTrigger className="h-4 w-24 font-mono text-[10px]" aria-label="Correction type">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                              {CORRECTION_TYPE_OPTIONS.map((t) => (
                                <SelectItem key={t} value={t} className="font-mono text-xs">{t}</SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                          <Badge
                            variant="outline"
                            className={`font-mono text-[10px] ${
                              c.confidence >= 0.8
                                ? "border-green-500/30 text-green-400"
                                : c.confidence >= 0.6
                                  ? "border-yellow-500/30 text-yellow-400"
                                  : "border-red-500/30 text-red-400"
                            }`}
                          >
                            {Math.round(c.confidence * 100)}%
                          </Badge>
                          {isLowConfidence && (
                            <AlertTriangle className="h-2.5 w-2.5 text-amber-400" />
                          )}
                        </div>
                        <p className="font-mono text-xs text-muted-foreground">{c.explanation}</p>
                        {c.assessmentNote && (
                          <p className="font-mono text-xs text-amber-400">
                            <AlertTriangle className="mr-1 inline h-2.5 w-2.5" />
                            {c.assessmentNote}
                          </p>
                        )}

                        {/* Collapsible diff */}
                        <button
                          type="button"
                          className="font-mono text-[10px] text-muted-foreground/70 hover:text-muted-foreground"
                          onClick={() => toggleBlock(idx)}
                          aria-expanded={expandedBlocks.has(idx)}
                        >
                          {expandedBlocks.has(idx) ? (
                            <ChevronDown className="mr-0.5 inline h-2.5 w-2.5" />
                          ) : (
                            <ChevronRight className="mr-0.5 inline h-2.5 w-2.5" />
                          )}
                          View diff
                        </button>
                        {expandedBlocks.has(idx) && (
                          <div className="space-y-1 rounded border border-border/30 bg-black/20 p-1.5">
                            {c.originalSnippet && c.originalSnippet !== "(no removed lines)" && (
                              <pre className="whitespace-pre-wrap font-mono text-[10px] leading-relaxed text-red-400/80">
                                {c.originalSnippet.split("\n").map((line: string, li: number) => (
                                  <div key={li}>- {line}</div>
                                ))}
                              </pre>
                            )}
                            {c.correctedSnippet && c.correctedSnippet !== "(no added lines)" && (
                              <pre className="whitespace-pre-wrap font-mono text-[10px] leading-relaxed text-green-400/80">
                                {c.correctedSnippet.split("\n").map((line: string, li: number) => (
                                  <div key={li}>+ {line}</div>
                                ))}
                              </pre>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          ))}
        </div>

        <div className="flex gap-1.5 pt-1">
          <Button
            size="sm"
            variant="outline"
            className="h-6 gap-1 px-2 font-mono text-xs border-green-500/30 text-green-400 hover:bg-green-500/10"
            onClick={onSavePatterns}
            disabled={checkedCount === 0}
          >
            <Check className="h-2.5 w-2.5" />
            Save {checkedCount} Pattern{checkedCount !== 1 ? "s" : ""}
          </Button>
          <Button
            size="sm"
            variant="ghost"
            className="h-6 px-2 font-mono text-xs"
            onClick={onSkip}
          >
            Cancel
          </Button>
        </div>
      </div>
    );
  }

  // --- Saving ---
  if (state === "saving") {
    return (
      <div className="space-y-2 rounded-lg border border-blue-500/20 bg-blue-500/5 p-3">
        <div className="flex items-center gap-2">
          <Loader2 className="h-3.5 w-3.5 animate-spin text-blue-400" />
          <span className="font-mono text-sm text-blue-400">Saving patterns...</span>
        </div>
      </div>
    );
  }

  // --- Done ---
  return (
    <div className="space-y-2 rounded-lg border border-green-500/20 bg-green-500/5 p-3">
      <div className="flex items-center gap-2">
        <CheckCircle2 className="h-3.5 w-3.5 text-green-400" />
        <span className="font-mono text-sm font-medium text-green-400">
          {savedCount > 0 ? `${savedCount} pattern${savedCount !== 1 ? "s" : ""} saved.` : "Fix complete."}
        </span>
      </div>
      <Button
        size="sm"
        variant="ghost"
        className="h-6 px-3 font-mono text-xs"
        onClick={onDismiss}
      >
        Dismiss
      </Button>
    </div>
  );
}

// --- Stuck panel: shows remaining errors with code context ---

function StuckPanel({ stuck }: { stuck: CompileFixStuckInfo }) {
  // Group errors by artifact
  const grouped: Record<string, CompileErrorInfo[]> = {};
  for (const err of stuck.errors) {
    const key = err.artifact_name ?? "Unknown";
    if (!grouped[key]) grouped[key] = [];
    grouped[key].push(err);
  }

  return (
    <div className="space-y-2 rounded-lg border border-red-500/20 bg-red-500/5 p-3">
      <div className="flex items-center gap-2">
        <AlertTriangle className="h-3.5 w-3.5 text-red-400" />
        <span className="font-mono text-sm font-medium text-red-400">
          Unable to resolve — {stuck.errors.length} error(s) after {stuck.rounds} round(s)
        </span>
      </div>
      <div className="font-mono text-xs text-muted-foreground">
        {stuck.reason}
      </div>

      {Object.entries(grouped).map(([artifact, errors]) => {
        const source = stuck.sources[artifact];
        const sourceLines = source?.split("\n");

        return (
          <div key={artifact} className="space-y-1">
            <div className="font-mono text-xs font-medium text-red-300">
              {artifact}
            </div>
            {errors.map((err, i) => (
              <div key={i} className="space-y-0.5">
                <div className="flex items-start gap-1.5">
                  <XCircle className="mt-0.5 h-2.5 w-2.5 shrink-0 text-red-400" />
                  <span className="font-mono text-xs text-red-300">
                    {err.line != null && <span className="text-red-300 font-medium">Line {err.line}: </span>}
                    {err.error_text}
                  </span>
                </div>
                {/* Show code context around the error line */}
                {err.line != null && sourceLines && (
                  <CodeContext lines={sourceLines} errorLine={err.line} />
                )}
              </div>
            ))}
          </div>
        );
      })}

      <div className="pt-1 font-mono text-xs text-muted-foreground">
        Type additional instructions below to try a different approach, or clear to start over.
      </div>
    </div>
  );
}

// --- Code context: shows ~3 lines around the error with the error line highlighted ---

function CodeContext({ lines, errorLine }: { lines: string[]; errorLine: number }) {
  const start = Math.max(0, errorLine - 3);
  const end = Math.min(lines.length, errorLine + 2);
  const contextLines = lines.slice(start, end);

  return (
    <div className="ml-4 overflow-x-auto rounded border border-red-500/10 bg-black/30">
      <pre className="whitespace-pre-wrap break-all px-2 py-1 font-mono text-xs leading-relaxed">
        {contextLines.map((line, i) => {
          const lineNum = start + i + 1;
          const isError = lineNum === errorLine;
          return (
            <div
              key={lineNum}
              className={isError ? "bg-red-500/20 text-red-300" : "text-muted-foreground"}
            >
              <span className="mr-2 inline-block w-4 text-right opacity-50">{lineNum}</span>
              {line}
            </div>
          );
        })}
      </pre>
    </div>
  );
}

// --- Message bubble component ---

function MessageBubble({
  message,
  index,
  isLoading,
  isConnected,
  autoRunning,
  onApplyFixes,
}: {
  message: CompileFixMessage;
  index: number;
  isLoading: boolean;
  isConnected: boolean;
  autoRunning: boolean;
  onApplyFixes: (fixes: FixedSource[], index: number) => void;
}) {
  const [expandedFixes, setExpandedFixes] = useState<Set<number>>(new Set());

  function toggleFix(fixIndex: number) {
    setExpandedFixes((prev) => {
      const next = new Set(prev);
      if (next.has(fixIndex)) next.delete(fixIndex);
      else next.add(fixIndex);
      return next;
    });
  }

  if (message.role === "system") {
    const isSuccess = message.content.includes("successful");
    const isFail = message.content.includes("failed") || message.content.includes("Error:");
    const isInProgress = message.content.includes("Recompiling") || message.content.includes("Continuing");
    return (
      <div className="flex items-center justify-center gap-1.5 py-1">
        {isSuccess && <CheckCircle2 className="h-2.5 w-2.5 text-green-400" />}
        {isFail && <XCircle className="h-2.5 w-2.5 text-red-400" />}
        {!isSuccess && !isFail && (
          isInProgress
            ? <Loader2 className="h-2.5 w-2.5 animate-spin text-muted-foreground" />
            : <span className="inline-block h-2 w-2 shrink-0 rounded-full bg-muted-foreground/40" />
        )}
        <span
          className={`font-mono text-xs ${
            isSuccess ? "text-green-400" : isFail ? "text-red-400" : "text-muted-foreground"
          }`}
        >
          {message.content}
        </span>
      </div>
    );
  }

  if (message.role === "user") {
    return (
      <div className="flex justify-end">
        <div className="flex max-w-[85%] items-start gap-1.5">
          <div className="min-w-0 rounded-lg bg-primary/10 px-2.5 py-1.5">
            <p className="break-words whitespace-pre-wrap font-mono text-sm">{message.content}</p>
          </div>
          <User className="mt-1 h-3 w-3 shrink-0 text-muted-foreground" />
        </div>
      </div>
    );
  }

  // Assistant message
  return (
    <div className="flex justify-start">
      <div className="flex max-w-[90%] items-start gap-1.5">
        <Bot className="mt-1 h-3 w-3 shrink-0 text-amber-400" />
        <div className="min-w-0 space-y-2">
          {/* Explanation text */}
          <div className="rounded-lg bg-muted/50 px-2.5 py-1.5">
            <p className="break-words whitespace-pre-wrap font-mono text-sm">{message.content}</p>
          </div>

          {/* Fixed code blocks */}
          {message.fixes && message.fixes.length > 0 && (
            <div className="space-y-1">
              <div className="font-mono text-xs font-medium text-muted-foreground">
                CORRECTED FILES ({message.fixes.length})
              </div>
              {message.fixes.map((fix, fi) => (
                <div key={fi} className="rounded border border-border/50 bg-muted/30">
                  <button
                    type="button"
                    className="flex w-full items-center gap-1.5 px-2 py-1 text-left hover:bg-muted/50"
                    onClick={() => toggleFix(fi)}
                    aria-expanded={expandedFixes.has(fi)}
                  >
                    {expandedFixes.has(fi) ? (
                      <ChevronDown className="h-2.5 w-2.5" />
                    ) : (
                      <ChevronRight className="h-2.5 w-2.5" />
                    )}
                    <span className="font-mono text-xs font-medium">{fix.artifactName}</span>
                    <Badge variant="outline" className="ml-auto font-mono text-xs">
                      {fix.content.split("\n").length} lines
                    </Badge>
                  </button>
                  {expandedFixes.has(fi) && (
                    <div className="max-h-48 overflow-auto border-t px-2 py-1">
                      <pre className="whitespace-pre-wrap break-words font-mono text-xs text-muted-foreground">
                        {fix.content}
                      </pre>
                    </div>
                  )}
                </div>
              ))}

              {/* Manual apply button — only when not auto-running */}
              {!message.appliedFixes && !autoRunning && (
                <Button
                  size="sm"
                  variant="outline"
                  className="h-6 w-full gap-1 font-mono text-xs"
                  onClick={() => onApplyFixes(message.fixes!, index)}
                  disabled={isLoading || !isConnected}
                >
                  <Play className="h-2.5 w-2.5" />
                  Apply & Recompile
                </Button>
              )}
              {message.appliedFixes && (
                <div className="py-0.5 text-center font-mono text-xs text-green-400">
                  Applied
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
