import { useRef, useState } from "react";
import { callNonStreaming } from "@/hooks/use-generation";
import { useUpdateMigrationSession } from "@/hooks/use-migrate-session";
import { useCreatePatternCandidate, useActivePatterns } from "@/hooks/use-patterns";
import {
  buildMigrationAnalysisSystemPrompt,
  buildMigrationAnalysisUserMessage,
  buildMigrationTransformSystemPrompt,
  buildMigrationTransformBatchUserMessage,
  buildMigrationSTLTransformSystemPrompt,
  buildMigrationSTLTransformUserMessage,
  buildMigrationReportSystemPrompt,
  buildMigrationReportUserMessage,
  ANALYSIS_BATCH_SIZE,
} from "@/lib/migrate-prompts";
import {
  buildMigrationCompileFixSystemPrompt,
  buildMigrationCompileFixUserMessage,
} from "@/lib/migrate-compile-fix-prompt";
import { getRelevantReferenceSections } from "@/lib/reference-lookup";
import {
  applyDeterministicTransforms,
  postProcessMigratedScl,
  inferBlockType,
  buildSpaceRenameMap,
  applyProjectWideSpaceRenames,
  inlineStandaloneTimerDbs,
} from "@/lib/migrate-deterministic";
import { parseGraphXml } from "@/lib/migrate-graph-parser";
import { parseLadXml } from "@/lib/migrate-lad-parser";
import type { MigrationSession, MigrationPlanStep, MigratedBlock, MigrationChangeType, FlaggedDecision } from "@/types";

export interface MigratePipelineState {
  running: boolean;
  currentBlockName: string | null;
  currentBlockDescription: string | null;
  scanProgress: number;
  totalBlocks: number;
  error: string | null;
}

// ---------------------------------------------------------------------------
// Local SCL scanner — extracts block type + first comment (no AI call)
// ---------------------------------------------------------------------------

function scanBlockInfo(scl: string): { blockType: string; description: string } {
  const typePatterns: Array<[RegExp, string]> = [
    [/FUNCTION_BLOCK\s/i, "Function Block (FB)"],
    [/ORGANIZATION_BLOCK\s/i, "Organization Block (OB)"],
    [/DATA_BLOCK\s/i, "Data Block (DB)"],
    [/FUNCTION\s/i, "Function (FC)"],
    [/TYPE\s/i, "User Data Type (UDT)"],
  ];
  let blockType = "Block";
  for (const [pattern, label] of typePatterns) {
    if (pattern.test(scl)) { blockType = label; break; }
  }

  // First block comment (* ... *) or line comment // ...
  const blockComment = scl.match(/\(\*\s*([\s\S]*?)\s*\*\)/);
  const lineComment = scl.match(/\/\/\s*(.+)/);
  const description = blockComment
    ? blockComment[1].replace(/\s+/g, " ").trim().slice(0, 120)
    : lineComment
    ? lineComment[1].trim().slice(0, 120)
    : "";

  return { blockType, description };
}

function extractErrorMessage(err: unknown): string {
  if (err instanceof Error) return err.message;
  if (typeof err === "object" && err !== null && "message" in err)
    return String((err as { message: unknown }).message);
  return String(err);
}

/**
 * Filter out S7_Optimized_Access advisory flags generated by the AI.
 * Policy: preserve the attribute as-is — no flags needed, engineer already knows.
 */
function filterOptimizedAccessFlags<T extends { id?: string; location?: string; issue?: string }>(
  flags: T[],
): T[] {
  return flags.filter((f) => {
    const text = `${f.id ?? ""} ${f.location ?? ""} ${f.issue ?? ""}`.toLowerCase();
    return !text.includes("s7_optimized_access") && !text.includes("optimised access") && !text.includes("optimized access");
  });
}

/** One compile error entry as captured from the WebSocket/job poll */
export interface CompileErrorEntry {
  artifactName: string;
  errorText: string;
  line?: number | null;
  column?: number | null;
  severity?: "ERROR" | "WARNING" | "INFO";
}

/** Result returned by runCompileFix */
export interface CompileFixResult {
  fixedCount: number;
  patternsSaved: number;
  couldNotFix: string[];
}

/**
 * Salvage completed objects from a truncated JSON array.
 * e.g. `[{...}, {...}, {` → `[{...}, {...}]`
 */
function recoverPartialJsonArray(raw: string): unknown[] {
  // Find the last occurrence of `}` followed only by optional whitespace/commas up to the end
  const lastClose = raw.lastIndexOf("}");
  if (lastClose === -1) return [];
  const candidate = raw.slice(0, lastClose + 1).trimEnd();
  // Strip trailing comma then close the array
  const closed = candidate.replace(/,\s*$/, "") + "]";
  // Ensure it starts with `[`
  const normalized = closed.trimStart().startsWith("[") ? closed : "[" + closed;
  try {
    const parsed = JSON.parse(normalized) as unknown;
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

export function useMigratePipeline() {
  const abortRef = useRef<AbortController | null>(null);
  const updateSession = useUpdateMigrationSession();
  const createPattern = useCreatePatternCandidate();
  const { data: migrationPatterns } = useActivePatterns("SIEMENS_MIGRATION");

  const [state, setState] = useState<MigratePipelineState>({
    running: false,
    currentBlockName: null,
    currentBlockDescription: null,
    scanProgress: 0,
    totalBlocks: 0,
    error: null,
  });

  function abort() {
    abortRef.current?.abort();
  }

  // -------------------------------------------------------------------------
  // Analysis
  // -------------------------------------------------------------------------

  async function runAnalysis(session: MigrationSession): Promise<void> {
    const controller = new AbortController();
    abortRef.current = controller;

    // Pre-scan all blocks locally (instant — no API call)
    const blockInfos = Object.entries(session.source_blocks).map(([name, scl]) => {
      const { blockType, description } = scanBlockInfo(scl);
      return { name, blockType, description };
    });

    setState({
      running: true,
      currentBlockName: blockInfos[0]?.name ?? null,
      currentBlockDescription: null,
      scanProgress: 0,
      totalBlocks: blockInfos.length,
      error: null,
    });

    // Cycle through block names while the AI processes — stop at the end
    let scanIdx = 0;
    const intervalId = window.setInterval(() => {
      if (scanIdx >= blockInfos.length) {
        window.clearInterval(intervalId);
        setState((s) => ({
          ...s,
          currentBlockName: "Compiling migration plan…",
          currentBlockDescription: null,
          scanProgress: blockInfos.length,
        }));
        return;
      }
      const info = blockInfos[scanIdx];
      setState((s) => ({
        ...s,
        currentBlockName: info.name,
        currentBlockDescription: info.description
          ? `${info.blockType} — ${info.description}`
          : info.blockType,
        scanProgress: scanIdx + 1,
      }));
      scanIdx++;
    }, 220);

    try {
      // Stop the scan animation — switching to batch progress display
      window.clearInterval(intervalId);

      // One reference lookup shared across all batches (avoids per-batch bloat)
      setState((s) => ({ ...s, currentBlockName: "Looking up reference docs…", currentBlockDescription: null }));
      const refContext = `S7-300 S7-400 migration to S7-1500 TIA Portal: deprecated instructions, OB restructuring, timer counter syntax, block optimisation, symbolic addressing, communication blocks`;
      const referenceSections = await getRelevantReferenceSections(
        refContext,
        "generation_request",
        "SIEMENS_MIGRATION",
        controller.signal,
        6,
        undefined,
        "SCL",
      );

      const systemPrompt = buildMigrationAnalysisSystemPrompt(referenceSections);

      // Split blocks into batches to stay within Edge Function compute limits
      const langs = session.source_block_languages ?? {};
      const allBlocks = Object.entries(session.source_blocks).map(([name, src]) => ({ name, src, lang: langs[name] }));
      const batches: Array<typeof allBlocks> = [];
      for (let i = 0; i < allBlocks.length; i += ANALYSIS_BATCH_SIZE) {
        batches.push(allBlocks.slice(i, i + ANALYSIS_BATCH_SIZE));
      }

      let completedBatches = 0;
      setState((s) => ({
        ...s,
        currentBlockName: `0 / ${batches.length} batches complete`,
        currentBlockDescription: `Analysing ${allBlocks.length} blocks in ${batches.length} parallel batches`,
        scanProgress: 0,
      }));

      const batchResults = await Promise.all(
        batches.map(async (batch, batchIdx) => {
          const userMessage = buildMigrationAnalysisUserMessage(batch, batchIdx, batches.length);
          const { content } = await callNonStreaming(
            systemPrompt,
            [{ role: "user", content: userMessage }],
            controller.signal,
            16384
          );

          const stripped = content.replace(/^```(?:json)?\s*/i, "").replace(/\s*```\s*$/i, "").trim();
          let batchSteps: MigrationPlanStep[];
          try {
            const raw = JSON.parse(stripped) as unknown;
            if (!Array.isArray(raw)) throw new Error(`Batch ${batchIdx + 1} returned non-array`);
            batchSteps = raw as MigrationPlanStep[];
          } catch {
            // Response may be truncated mid-array — recover completed objects
            const recovered = recoverPartialJsonArray(stripped);
            if (recovered.length > 0) {
              console.warn(`Batch ${batchIdx + 1}: truncated JSON, recovered ${recovered.length} steps`);
              batchSteps = recovered as MigrationPlanStep[];
            } else {
              throw new Error(`Batch ${batchIdx + 1} returned invalid JSON: ${content.slice(0, 200)}`);
            }
          }

          completedBatches++;
          setState((s) => ({
            ...s,
            currentBlockName: `${completedBatches} / ${batches.length} batches complete`,
            scanProgress: Math.round((completedBatches / batches.length) * blockInfos.length),
          }));

          return { batchIdx, steps: batchSteps };
        })
      );

      // Re-order by original batch index and assign stable IDs
      const allPlanSteps: MigrationPlanStep[] = batchResults
        .sort((a, b) => a.batchIdx - b.batchIdx)
        .flatMap(({ steps }, i) =>
          steps.map((s, j) => ({ ...s, id: `step_${i * 1000 + j + 1}` }))
        );

      const plan = allPlanSteps;
      const breakingCount = plan.filter((s) => s.severity === "BREAKING").length;
      const warningCount = plan.filter((s) => s.severity === "WARNING").length;
      const infoCount = plan.filter((s) => s.severity === "INFO").length;
      const summary = `Found ${plan.length} migration items across ${Object.keys(session.source_blocks).length} blocks: ${breakingCount} BREAKING, ${warningCount} WARNING, ${infoCount} INFO.`;

      await updateSession.mutateAsync({
        id: session.id,
        updates: { migration_plan: plan, analysis_summary: summary, current_step: "approve_plan" },
      });
    } catch (err) {
      setState((s) => ({ ...s, error: extractErrorMessage(err) }));
      throw err;
    } finally {
      window.clearInterval(intervalId);
      setState((s) => ({ ...s, running: false, currentBlockName: null, currentBlockDescription: null }));
    }
  }

  // -------------------------------------------------------------------------
  // Transform — block by block
  // -------------------------------------------------------------------------

  async function runTransform(session: MigrationSession): Promise<void> {
    const controller = new AbortController();
    abortRef.current = controller;

    const allBlockEntries = Object.entries(session.source_blocks);

    setState({ running: true, currentBlockName: "Looking up reference docs…", currentBlockDescription: null, scanProgress: 0, totalBlocks: allBlockEntries.length, error: null });

    try {
      // One shared reference lookup for all blocks — avoids per-block AI call overhead
      const refContext = `S7-300 S7-400 migration to S7-1500: naming conventions, timer TON TOF TP, counter CTU CTD, symbolic addressing, block call syntax, data types TIME S5TIME`;
      const sharedRefSections = await getRelevantReferenceSections(
        refContext,
        "generation_request",
        "SIEMENS_MIGRATION",
        controller.signal,
        8,
        undefined,
        "SCL",
      );
      const sharedSystemPrompt = buildMigrationTransformSystemPrompt(
        sharedRefSections,
        migrationPatterns ?? [],
        session.target_cpu_order_number ?? undefined,
        session.source_plc_family ?? undefined,
      );

      // ── Pre-pass 1: rename all identifiers with spaces → underscores ──────────
      // Must happen before timer inlining so DB references match renamed keys.
      setState((s) => ({ ...s, currentBlockName: "Renaming identifiers with spaces…" }));
      const spaceRenames = buildSpaceRenameMap(session.source_blocks);
      const {
        blocks: renamedBlocks,
        langs: renamedLangs,
        changes: spaceRenameChanges,
      } = applyProjectWideSpaceRenames(
        session.source_blocks,
        session.source_block_languages ?? {},
        spaceRenames,
      );

      // ── Pre-pass 2: inline standalone S7-300 timer instance DBs ────────────
      // Detects TON_I/TOF_T/TP_I instance DBs, injects VAR_STAT into calling FBs,
      // marks the original DBs for deletion.
      setState((s) => ({ ...s, currentBlockName: "Inlining standalone timer DBs…" }));
      const { updatedBlocks: workingBlocks, timerDbNames, changes: timerInlineChanges } =
        inlineStandaloneTimerDbs(renamedBlocks);

      // Rebuild allBlockEntries from the pre-processed working blocks
      const workingLangs = renamedLangs;
      const workingEntries = Object.entries(workingBlocks);

      if (spaceRenameChanges.length > 0 || timerInlineChanges.length > 0) {
        console.info(
          "[transform pre-pass]",
          [...spaceRenameChanges, ...timerInlineChanges].join("\n"),
        );
      }

      // Lazily built STL prompt — only one build regardless of concurrency (JS is single-threaded)
      let stlSystemPromptPromise: Promise<string> | null = null;
      function getStlPrompt(): Promise<string> {
        if (!stlSystemPromptPromise)
          stlSystemPromptPromise = Promise.resolve(buildMigrationSTLTransformSystemPrompt());
        return stlSystemPromptPromise;
      }

      // Pre-sized results array keeps original block order
      const results: (MigratedBlock | null)[] = new Array(workingEntries.length).fill(null);
      let completedCount = 0;

      // Pending SCL blocks that need AI — collected during Phase 1, batched in Phase 2
      interface AiPendingBlock {
        blockIdx: number;
        blockName: string;
        originalScl: string;
        detScl: string;
        detChanges: string[];
        deterministicFlags: FlaggedDecision[];
        advisoryFlags: FlaggedDecision[];
        handledTypes: MigrationChangeType[];
      }
      const aiPending: AiPendingBlock[] = [];

      // ── Phase 1: Deterministic + non-AI blocks (parallel worker pool) ────────
      // SCL blocks that still need AI work are deferred to Phase 2.
      async function processDeterministic(i: number): Promise<void> {
        const [blockName, originalScl] = workingEntries[i];
        const blockLang = workingLangs[blockName] ?? "SCL";

        // Timer DBs that were inlined into callers → produce a deletion notice block
        if (timerDbNames.has(blockName)) {
          const inlineNote = timerInlineChanges.find((c) => c.includes(`"${blockName}"`)) ?? "";
          results[i] = {
            name: blockName,
            block_type: "DB",
            original_scl: session.source_blocks[blockName] ?? originalScl,
            migrated_scl: `(* TIMER DB INLINED — DELETE THIS BLOCK FROM TIA PORTAL\n\n${inlineNote}\n\nThis standalone S7-300 SFB instance DB is no longer needed on S7-1500.\nIEC timer instances are declared as VAR_STAT inside the calling FB.\nTIA Portal automatically creates a hidden system DB for each static timer instance.\n*)`,
            approved: false,
            changes_applied: [inlineNote || `Timer DB "${blockName}" was inlined into calling FB(s)`],
            flagged_decisions: [{
              id: "timer_inline_1",
              location: "entire block",
              issue: `This DATA_BLOCK was a standalone S7-300 SFB timer instance. It has been migrated to a static variable in the calling FB(s).`,
              original_code: "",
              proposed_solution: `Delete "${blockName}" from the TIA Portal project. The calling FB(s) now declare the timer as VAR_STAT — TIA Portal will manage the instance DB automatically under System blocks > Program resources.`,
              accepted: null as null,
            }],
          };
          completedCount++;
          setState((s) => ({ ...s, scanProgress: completedCount }));
          return;
        }

        setState((s) => ({ ...s, currentBlockName: blockName, currentBlockDescription: null }));

        let block: MigratedBlock | null = null;

        // ── GRAPH (SFC): parse XML, generate advisory — no AI call ───────────
        if (blockLang === "GRAPH") {
          const parsed = parseGraphXml(blockName, originalScl);
          const breakingCount = parsed.flags.filter((f) => f.severity === "BREAKING").length;
          block = {
            name: blockName,
            block_type: "FB",
            original_language: blockLang,
            original_scl: originalScl,
            migrated_scl: parsed.advisory,
            approved: false,
            changes_applied: [
              `GRAPH block — ${parsed.steps.length} step(s), ${parsed.transitions.length} transition(s) analysed`,
              ...(breakingCount > 0
                ? [`${breakingCount} BREAKING issue(s) flagged — fix in TIA Portal before recompiling`]
                : ["No issues detected — safe to recompile after CPU retarget"]),
            ],
            flagged_decisions: parsed.flags.map((flag, idx) => ({
              id: `graph_flag_${idx + 1}`,
              location: flag.location,
              issue: flag.issue,
              original_code: "",
              proposed_solution: flag.issue.includes("Absolute address")
                ? "Replace with symbolic tag name in TIA Portal GRAPH editor → open transition/action and update condition"
                : flag.issue.includes("SFC")
                ? "Replace with S7-1500 equivalent instruction — see migration plan for mapping"
                : "Review and update in TIA Portal GRAPH editor before recompiling",
              accepted: null as null,
            })),
          };
        }

        // ── LAD / FBD: parse XML, generate advisory — no AI call ─────────────
        else if (blockLang === "LAD" || blockLang === "FBD") {
          const parsed = parseLadXml(blockName, originalScl, blockLang);
          const breakingCount = parsed.flags.filter((f) => f.severity === "BREAKING").length;
          block = {
            name: blockName,
            block_type: inferBlockType(originalScl),
            original_language: blockLang,
            original_scl: originalScl,
            migrated_scl: parsed.advisory,
            approved: false,
            changes_applied: [
              `${blockLang} block — ${parsed.networks.length} network(s) analysed`,
              ...(breakingCount > 0
                ? [`${breakingCount} BREAKING issue(s) flagged — fix in TIA Portal before recompiling`]
                : ["No issues detected — safe to recompile after CPU retarget"]),
            ],
            flagged_decisions: parsed.flags.map((flag, idx) => ({
              id: `lad_flag_${idx + 1}`,
              location: flag.location,
              issue: flag.issue,
              original_code: "",
              proposed_solution: flag.issue.includes("Absolute address")
                ? `Replace with symbolic tag in TIA Portal ${blockLang} editor`
                : flag.issue.includes("timer") || flag.issue.includes("counter")
                ? "Replace instruction in TIA Portal LAD editor — drag IEC equivalent from instruction library"
                : "Review and update in TIA Portal before recompiling",
              accepted: null as null,
            })),
          };
        }

        // ── STL / AWL: AI converts to SCL (per-block, separate system prompt) ─
        else if (blockLang === "STL") {
          const stlPrompt = await getStlPrompt();
          const userMessage = buildMigrationSTLTransformUserMessage(blockName, originalScl);
          try {
            const { content } = await callNonStreaming(
              stlPrompt,
              [{ role: "user", content: userMessage }],
              controller.signal,
              16384,
            );
            const stripped = content.replace(/^```(?:json)?\s*/i, "").replace(/\s*```\s*$/i, "").trim();
            block = JSON.parse(stripped) as MigratedBlock;
            block.original_scl = originalScl;
            block.name = blockName;
            const post = postProcessMigratedScl(block.migrated_scl);
            block.migrated_scl = post.scl;
            if (post.cleanups.length > 0)
              block.changes_applied = [...(block.changes_applied ?? []), ...post.cleanups];
          } catch {
            block = {
              name: blockName,
              block_type: inferBlockType(originalScl),
              original_scl: originalScl,
              migrated_scl: `(* STL→SCL conversion failed — manual conversion required *)\n${originalScl}`,
              approved: false,
              changes_applied: ["STL→SCL AI conversion failed"],
              flagged_decisions: [{
                id: "flag_stl_1",
                location: "entire block",
                issue: "AI failed to parse or convert this STL block",
                original_code: originalScl.slice(0, 500),
                proposed_solution: "Manually convert STL to SCL in TIA Portal",
                accepted: null,
              }],
            };
          }
        }

        // ── SCL / DB: deterministic transforms — AI deferred to Phase 2 ──────
        else {
          const originalBlockName =
            [...spaceRenames.entries()].find(([, v]) => v === blockName)?.[0] ?? blockName;
          const approvedSteps = session.migration_plan.filter(
            (s) =>
              (s.block_name === blockName || s.block_name === originalBlockName) &&
              s.approved &&
              !s.skipped,
          );

          const {
            scl: detScl,
            changesApplied: detChanges,
            handledTypes,
            flaggedComments,
          } = applyDeterministicTransforms(originalScl, approvedSteps);

          const remainingSteps = approvedSteps.filter((s) => !handledTypes.includes(s.change_type));
          const infoOnlySteps = remainingSteps.filter((s) => s.severity === "INFO");
          const aiWorkSteps = remainingSteps.filter((s) => s.severity !== "INFO");

          const deterministicFlags: FlaggedDecision[] = flaggedComments.map((msg, idx) => ({
            id: `det_flag_${idx + 1}`,
            location: "deterministic transform",
            issue: msg,
            original_code: "",
            proposed_solution: "Handle reset logic manually — set IN := FALSE when reset required",
            accepted: null as null,
          }));

          const advisoryFlags: FlaggedDecision[] = infoOnlySteps.map((step) => ({
            id: `info_${step.id}`,
            location: `[${step.change_type}] ${blockName}`,
            issue: step.description,
            original_code: "",
            proposed_solution: step.action,
            accepted: null as null,
          }));

          if (aiWorkSteps.length === 0) {
            // No BREAKING/WARNING remain — fully deterministic, no AI needed
            block = {
              name: blockName,
              block_type: inferBlockType(detScl),
              original_scl: originalScl,
              migrated_scl: detScl,
              approved: false,
              changes_applied: detChanges,
              flagged_decisions: filterOptimizedAccessFlags([...deterministicFlags, ...advisoryFlags]),
            };
          } else {
            // Defer to Phase 2 batch AI processing
            aiPending.push({ blockIdx: i, blockName, originalScl, detScl, detChanges, deterministicFlags, advisoryFlags, handledTypes });
            return; // do NOT increment completedCount — Phase 2 handles it
          }
        }

        results[i] = block;
        completedCount++;
        setState((s) => ({ ...s, scanProgress: completedCount }));
      }

      // ── Run Phase 1 with concurrent worker pool ───────────────────────────
      const CONCURRENCY = 8;
      let nextIdx = 0;
      async function detWorker() {
        while (nextIdx < workingEntries.length) {
          if (controller.signal.aborted) break;
          const i = nextIdx++;
          await processDeterministic(i);
        }
      }
      await Promise.all(Array.from({ length: Math.min(CONCURRENCY, workingEntries.length) }, detWorker));

      // ── Phase 2: Batch AI calls for SCL blocks needing transform ─────────
      // Groups of 4 blocks per call — system prompt paid once per batch.
      const AI_BATCH_SIZE = 4;
      for (let b = 0; b < aiPending.length; b += AI_BATCH_SIZE) {
        if (controller.signal.aborted) break;
        const batch = aiPending.slice(b, b + AI_BATCH_SIZE);
        setState((s) => ({ ...s, currentBlockName: `AI transform: ${batch.map((x) => x.blockName).join(", ")}` }));

        const batchInput = batch.map((item) => ({
          blockName: item.blockName,
          scl: item.detScl,
          steps: session.migration_plan,
          handledTypes: item.handledTypes,
        }));

        let batchParsed: MigratedBlock[] | null = null;
        try {
          const { content } = await callNonStreaming(
            sharedSystemPrompt,
            [{ role: "user", content: buildMigrationTransformBatchUserMessage(batchInput) }],
            controller.signal,
            32768,
          );
          const stripped = content.replace(/^```(?:json)?\s*/i, "").replace(/\s*```\s*$/i, "").trim();
          batchParsed = JSON.parse(stripped) as MigratedBlock[];
        } catch (batchErr) {
          console.error(`AI batch transform failed (blocks ${b}–${b + batch.length - 1}):`, batchErr);
        }

        for (let j = 0; j < batch.length; j++) {
          const item = batch[j];
          const aiBlock = batchParsed?.[j];
          if (aiBlock) {
            aiBlock.original_scl = item.originalScl;
            aiBlock.name = item.blockName;
            aiBlock.changes_applied = [...item.detChanges, ...(aiBlock.changes_applied ?? [])];
            aiBlock.flagged_decisions = filterOptimizedAccessFlags([
              ...item.deterministicFlags,
              ...item.advisoryFlags,
              ...(aiBlock.flagged_decisions ?? []),
            ]);
            results[item.blockIdx] = aiBlock;
          } else {
            // Batch failed or response shorter than expected — fall back to deterministic-only
            results[item.blockIdx] = {
              name: item.blockName,
              block_type: inferBlockType(item.detScl),
              original_scl: item.originalScl,
              migrated_scl: item.detScl,
              approved: false,
              changes_applied: [...item.detChanges, batchParsed ? "AI response missing this block — deterministic changes only" : `AI batch failed — deterministic changes only`],
              flagged_decisions: filterOptimizedAccessFlags([...item.deterministicFlags, ...item.advisoryFlags]),
            };
          }
        }

        completedCount += batch.length;
        setState((s) => ({ ...s, scanProgress: completedCount }));
      }

      const finalResults = results.filter((b): b is MigratedBlock => b !== null);
      const totalFlags = finalResults.reduce((n, b) => n + (b.flagged_decisions?.length ?? 0), 0);

      await updateSession.mutateAsync({
        id: session.id,
        updates: {
          migrated_blocks: finalResults,
          current_step: totalFlags > 0 ? "transform" : "compile",
        },
      });
    } catch (err) {
      setState((s) => ({ ...s, error: extractErrorMessage(err) }));
      throw err;
    } finally {
      setState((s) => ({ ...s, running: false, currentBlockName: null }));
    }
  }

  // -------------------------------------------------------------------------
  // Report
  // -------------------------------------------------------------------------

  async function runReport(session: MigrationSession): Promise<void> {
    const controller = new AbortController();
    abortRef.current = controller;

    setState({ running: true, currentBlockName: "Report Generation", currentBlockDescription: null, scanProgress: 0, totalBlocks: 0, error: null });

    try {
      const systemPrompt = buildMigrationReportSystemPrompt();
      const userMessage = buildMigrationReportUserMessage(session);

      const { content } = await callNonStreaming(
        systemPrompt,
        [{ role: "user", content: userMessage }],
        controller.signal,
        8192
      );

      await updateSession.mutateAsync({
        id: session.id,
        updates: {
          report_markdown: content,
          current_step: "report",
        },
      });
    } finally {
      setState((s) => ({ ...s, running: false, currentBlockName: null }));
    }
  }

  // -------------------------------------------------------------------------
  // Compile-fix loop — called manually after compile errors appear
  // -------------------------------------------------------------------------

  async function runCompileFix(
    session: MigrationSession,
    errors: CompileErrorEntry[],
  ): Promise<CompileFixResult> {
    const controller = new AbortController();
    abortRef.current = controller;

    setState((s) => ({
      ...s,
      running: true,
      currentBlockName: "Analysing compile errors…",
      currentBlockDescription: null,
      error: null,
    }));

    try {
      // Group errors by block name, formatting location info when available
      const errorsByBlock = new Map<string, string[]>();
      for (const { artifactName, errorText, line, column } of errors) {
        if (!errorsByBlock.has(artifactName)) errorsByBlock.set(artifactName, []);
        const location = line != null ? ` [line ${line}${column != null ? `:${column}` : ""}]` : "";
        errorsByBlock.get(artifactName)!.push(`${location} ${errorText}`.trim());
      }

      // Build blocks payload — only blocks that have errors AND migrated SCL
      const blocksToFix = Array.from(errorsByBlock.entries()).flatMap(([name, errs]) => {
        const block = session.migrated_blocks.find((b) => b.name === name);
        if (!block) return [];
        return [{ name, scl: block.migrated_scl, errors: errs }];
      });

      if (blocksToFix.length === 0) {
        return { fixedCount: 0, patternsSaved: 0, couldNotFix: [] };
      }

      setState((s) => ({
        ...s,
        currentBlockName: `Fixing ${blocksToFix.length} block(s)…`,
        totalBlocks: blocksToFix.length,
        scanProgress: 0,
      }));

      const systemPrompt = buildMigrationCompileFixSystemPrompt();
      const userMessage = buildMigrationCompileFixUserMessage(blocksToFix);

      const { content } = await callNonStreaming(
        systemPrompt,
        [{ role: "user", content: userMessage }],
        controller.signal,
        16384,
      );

      const stripped = content.replace(/^```(?:json)?\s*/i, "").replace(/\s*```\s*$/i, "").trim();
      type FixEntry = {
        name: string;
        fixed_scl: string;
        corrections: Array<{
          error_fixed: string;
          change_made: string;
          original_snippet: string;
          fixed_snippet: string;
          correction_type: string;
        }>;
        could_not_fix: string[];
      };
      let fixEntries: FixEntry[];
      try {
        fixEntries = JSON.parse(stripped) as FixEntry[];
      } catch {
        throw new Error(`Compile-fix agent returned invalid JSON: ${content.slice(0, 200)}`);
      }

      // Apply fixes to session blocks
      const updatedBlocks = session.migrated_blocks.map((block) => {
        const fix = fixEntries.find((f) => f.name === block.name);
        if (!fix || !fix.fixed_scl) return block;
        return { ...block, migrated_scl: fix.fixed_scl };
      });

      await updateSession.mutateAsync({
        id: session.id,
        updates: { migrated_blocks: updatedBlocks },
      });

      // Save corrections as PENDING migration patterns (one per correction, not per block)
      let patternsSaved = 0;
      const couldNotFix: string[] = [];

      for (const fix of fixEntries) {
        couldNotFix.push(...(fix.could_not_fix ?? []));

        for (const correction of fix.corrections ?? []) {
          if (!correction.original_snippet || !correction.fixed_snippet) continue;
          if (correction.original_snippet.trim() === correction.fixed_snippet.trim()) continue;

          try {
            await createPattern.mutateAsync({
              plc_brand: "SIEMENS_MIGRATION",
              device_type: fix.name,
              context: `S7-300→S7-1500 compile fix: ${correction.error_fixed}`,
              original_snippet: correction.original_snippet,
              corrected_snippet: correction.fixed_snippet,
              correction_type: correction.correction_type ?? "OTHER",
              explanation_tag: correction.change_made,
            });
            patternsSaved++;
          } catch {
            // Non-fatal — pattern save failure shouldn't block the fix
          }
        }
      }

      setState((s) => ({ ...s, scanProgress: blocksToFix.length }));
      return { fixedCount: fixEntries.length, patternsSaved, couldNotFix };
    } catch (err) {
      setState((s) => ({ ...s, error: extractErrorMessage(err) }));
      throw err;
    } finally {
      setState((s) => ({ ...s, running: false, currentBlockName: null, currentBlockDescription: null }));
    }
  }

  return {
    ...state,
    runAnalysis,
    runTransform,
    runReport,
    runCompileFix,
    abort,
  };
}
