param([string]$jsonPath, [string]$outputTs)

$json = Get-Content $jsonPath -Raw | ConvertFrom-Json

$sb = New-Object System.Text.StringBuilder
$null = $sb.AppendLine("/**")
$null = $sb.AppendLine(" * Open Library V19 Unified udtHMI_* tag contract catalog.")
$null = $sb.AppendLine(" *")
$null = $sb.AppendLine(" * Field definitions extracted from SimaticML XML exports of the actual library UDTs")
$null = $sb.AppendLine(" * imported into TIA Portal V20 via the wizard reference project.")
$null = $sb.AppendLine(" * Source: Docs/HMI Reference/wizard-output/udts/udtHMI_*.xml")
$null = $sb.AppendLine(" *")
$null = $sb.AppendLine(" * Generated by bridge/emit-udt-catalog.ps1. Do not hand-edit. Re-run the")
$null = $sb.AppendLine(" * Export Reference endpoint + script if the library version changes.")
$null = $sb.AppendLine(" */")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("export interface UdtField {")
$null = $sb.AppendLine("  /** Field name with Hungarian-style prefix, e.g. 'iMode', 'bPB_Reverse', 'rSetpoint' */")
$null = $sb.AppendLine("  name: string;")
$null = $sb.AppendLine("  /** Siemens SCL data type: Int, Bool, Real, Word, DInt, Time, Byte, etc. */")
$null = $sb.AppendLine("  dataType: string;")
$null = $sb.AppendLine("  /** True when HMI can write to this field (PLC reads it). False means PLC-written, HMI read-only. */")
$null = $sb.AppendLine("  hmiWritable: boolean;")
$null = $sb.AppendLine("  /** English comment from the library describing the field purpose */")
$null = $sb.AppendLine("  comment: string;")
$null = $sb.AppendLine("}")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("export interface UdtDefinition {")
$null = $sb.AppendLine("  name: string;")
$null = $sb.AppendLine("  fields: UdtField[];")
$null = $sb.AppendLine("}")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("/**")
$null = $sb.AppendLine(" * Full catalog keyed by UDT name. Used by Phase 3.4 tag mapping layer to resolve")
$null = $sb.AppendLine(" * which fields of a given udtHMI_* struct need to be populated from a device's")
$null = $sb.AppendLine(" * IO signals and which fields are PLC outputs that flow back into the HMI.")
$null = $sb.AppendLine(" */")
$null = $sb.AppendLine("export const OPEN_LIBRARY_UDT_CATALOG: Record<string, UdtDefinition> = {")

$udtNames = $json.PSObject.Properties | ForEach-Object { $_.Name } | Sort-Object
foreach ($udtName in $udtNames) {
    $fields = $json.$udtName
    $null = $sb.AppendLine("  `"$udtName`": {")
    $null = $sb.AppendLine("    name: `"$udtName`",")
    $null = $sb.AppendLine("    fields: [")
    foreach ($f in $fields) {
        $name = $f.name
        $dt = $f.dataType
        # Strip surrounding quotes when datatype refers to another UDT
        if ($dt) { $dt = $dt.Trim('"') }
        $w = if ($f.hmiWritable) { 'true' } else { 'false' }
        $c = $f.comment
        if ($c) {
            $c = $c.Replace('\', '\\').Replace('"', '\"').Replace("`r", ' ').Replace("`n", ' ').Trim()
        } else {
            $c = ''
        }
        $null = $sb.AppendLine("      { name: `"$name`", dataType: `"$dt`", hmiWritable: $w, comment: `"$c`" },")
    }
    $null = $sb.AppendLine("    ],")
    $null = $sb.AppendLine("  },")
}
$null = $sb.AppendLine("};")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("/** Look up a UDT by name. Returns null when no match exists. */")
$null = $sb.AppendLine("export function getUdtDefinition(name: string): UdtDefinition | null {")
$null = $sb.AppendLine("  return OPEN_LIBRARY_UDT_CATALOG[name] ?? null;")
$null = $sb.AppendLine("}")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("/**")
$null = $sb.AppendLine(" * Filter a UDT's fields by direction.")
$null = $sb.AppendLine(" *   hmiWritable=true: HMI writes to PLC (commands, pushbuttons, setpoints)")
$null = $sb.AppendLine(" *   hmiWritable=false: PLC writes to HMI (status, feedback, actual values)")
$null = $sb.AppendLine(" */")
$null = $sb.AppendLine("export function getFieldsByDirection(udtName: string, hmiWritable: boolean): UdtField[] {")
$null = $sb.AppendLine("  const udt = getUdtDefinition(udtName);")
$null = $sb.AppendLine("  if (!udt) return [];")
$null = $sb.AppendLine("  return udt.fields.filter((f) => f.hmiWritable === hmiWritable);")
$null = $sb.AppendLine("}")

Set-Content -Path $outputTs -Value $sb.ToString() -Encoding UTF8
Write-Host "Wrote $($udtNames.Count) UDTs to $outputTs"
