param([string]$jsonPath, [string]$outputTs)

$json = Get-Content $jsonPath -Raw | ConvertFrom-Json

$sb = New-Object System.Text.StringBuilder
$null = $sb.AppendLine("/**")
$null = $sb.AppendLine(" * WinCC Unified HMI screen item type catalog (V20).")
$null = $sb.AppendLine(" *")
$null = $sb.AppendLine(" * Every concrete subclass of Siemens.Engineering.HmiUnified.UI.Base.HmiScreenItemBase")
$null = $sb.AppendLine(" * with its publicly writable properties. Used by Pac-Forge to:")
$null = $sb.AppendLine(" *   1. Validate item type names before emitting payloads")
$null = $sb.AppendLine(" *   2. Check attribute names for each type")
$null = $sb.AppendLine(" *   3. Tell the bridge which .NET Type to pass to CreateCompositeItem<T>() via fullName")
$null = $sb.AppendLine(" *")
$null = $sb.AppendLine(" * Generated by bridge/reflect-screen-items.ps1 + bridge/emit-item-types.ps1.")
$null = $sb.AppendLine(" * Re-run both when upgrading to a newer TIA Portal version.")
$null = $sb.AppendLine(" */")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("export type HmiItemCategory = `"Shapes`" | `"Widgets`" | `"Controls`" | `"Screens`" | `"Base`";")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("export interface HmiItemPropertySpec {")
$null = $sb.AppendLine("  /** PascalCase Openness attribute name, e.g. BackColor, Width, IsEnabled */")
$null = $sb.AppendLine("  name: string;")
$null = $sb.AppendLine("  /** .NET type name: Color, UInt32, Boolean, HmiFillPattern, ... */")
$null = $sb.AppendLine("  typeName: string;")
$null = $sb.AppendLine("  isEnum: boolean;")
$null = $sb.AppendLine("  enumValues: string[];")
$null = $sb.AppendLine("}")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("export interface HmiItemTypeSpec {")
$null = $sb.AppendLine("  /** Short type name, e.g. HmiRectangle */")
$null = $sb.AppendLine("  name: string;")
$null = $sb.AppendLine("  /** Fully qualified .NET type name, used by the bridge for generic dispatch */")
$null = $sb.AppendLine("  fullName: string;")
$null = $sb.AppendLine("  namespace: string;")
$null = $sb.AppendLine("  category: HmiItemCategory;")
$null = $sb.AppendLine("  properties: HmiItemPropertySpec[];")
$null = $sb.AppendLine("}")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("export const HMI_ITEM_TYPES: Record<string, HmiItemTypeSpec> = {")

$typeNames = $json.PSObject.Properties | ForEach-Object { $_.Name } | Sort-Object
foreach ($typeName in $typeNames) {
    $spec = $json.$typeName
    $cat = $spec.category
    if ($cat -eq '' -or -not $cat) { $cat = 'Base' }

    $null = $sb.AppendLine("  `"$typeName`": {")
    $null = $sb.AppendLine("    name: `"$typeName`",")
    $null = $sb.AppendLine("    fullName: `"$($spec.fullName)`",")
    $null = $sb.AppendLine("    namespace: `"$($spec.namespace)`",")
    $null = $sb.AppendLine("    category: `"$cat`",")
    $null = $sb.AppendLine("    properties: [")
    foreach ($p in $spec.properties) {
        $ev = ''
        if ($p.enumValues -and $p.enumValues.Count -gt 0) {
            $ev = ($p.enumValues | ForEach-Object { "`"$_`"" }) -join ", "
        }
        $isEnum = if ($p.isEnum) { 'true' } else { 'false' }
        $null = $sb.AppendLine("      { name: `"$($p.name)`", typeName: `"$($p.typeName)`", isEnum: $isEnum, enumValues: [$ev] },")
    }
    $null = $sb.AppendLine("    ],")
    $null = $sb.AppendLine("  },")
}
$null = $sb.AppendLine("};")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("/** Look up a type spec by short name. */")
$null = $sb.AppendLine("export function getItemTypeSpec(name: string): HmiItemTypeSpec | null {")
$null = $sb.AppendLine("  return HMI_ITEM_TYPES[name] ?? null;")
$null = $sb.AppendLine("}")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("/** Return the set of valid attribute names for a given item type, or empty if unknown. */")
$null = $sb.AppendLine("export function getValidAttributes(typeName: string): Set<string> {")
$null = $sb.AppendLine("  const spec = getItemTypeSpec(typeName);")
$null = $sb.AppendLine("  if (!spec) return new Set();")
$null = $sb.AppendLine("  return new Set(spec.properties.map((p) => p.name));")
$null = $sb.AppendLine("}")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("/** Check whether an attribute name is valid for a given item type. */")
$null = $sb.AppendLine("export function isValidAttribute(typeName: string, attrName: string): boolean {")
$null = $sb.AppendLine("  return getValidAttributes(typeName).has(attrName);")
$null = $sb.AppendLine("}")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("/** List all item types in a given category. */")
$null = $sb.AppendLine("export function getItemTypesByCategory(category: HmiItemCategory): HmiItemTypeSpec[] {")
$null = $sb.AppendLine("  return Object.values(HMI_ITEM_TYPES).filter((t) => t.category === category);")
$null = $sb.AppendLine("}")

Set-Content -Path $outputTs -Value $sb.ToString() -Encoding UTF8
Write-Host "Wrote $($typeNames.Count) item types to $outputTs"
